<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><EmbeddedResource Include="../../localization/en.json" LogicalName="Reaper.Core.English.json" /><EmbeddedResource Include="KnownFixes.json" LogicalName="Reaper.Core.KnownFixes.json" /></ItemGroup></Project>
