const {chromium}=require(require.resolve('playwright',{paths:[require('node:path').join(__dirname,'..','ui')]}));
const assert=require('node:assert/strict');
const url=process.env.REAPER_PREVIEW_URL||'http://127.0.0.1:5199/';
(async()=>{
 const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByRole('heading',{name:'Grab your guns. Launch your games.'}).waitFor();
 assert.equal(await page.locator('html').getAttribute('lang'),'en','English is the first-run default');
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByRole('button',{name:'Deutsch',exact:true}).click();
 await page.getByRole('button',{name:'Meine Guns',exact:true}).click();
 await page.getByRole('heading',{name:'Deine Gun. Dein Setup.'}).waitFor();
 await page.getByText('USB · 4 IR-Punkte',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Einstellungen',exact:true}).click();
 await page.getByRole('button',{name:'English',exact:true}).click();
 await page.getByRole('button',{name:'My Guns',exact:true}).click();
 await page.getByRole('heading',{name:'Your gun. Your setup.'}).waitFor();
 await page.getByText('USB · 4 IR points',{exact:true}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'English',exact:true}).getAttribute('aria-pressed'),'true','English choice survives reload');
 await page.getByRole('button',{name:'Deutsch',exact:true}).click();
 await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'de','German choice survives reload');
 await page.getByRole('button',{name:'Spielen',exact:true}).click();
 await page.getByRole('heading',{name:'Guns nehmen. Spiele starten.'}).waitFor();
 assert.equal(await page.locator('.game-tile').count(),0,'No fabricated installed library');
 await page.getByRole('button',{name:'Mit Beispielspielen ansehen'}).click();
 assert.equal(await page.locator('.game-tile').count(),8);
 await page.getByRole('button',{name:'Time Crisis 5 auswählen'}).click();
 await page.getByRole('heading',{name:'Time Crisis 5',exact:true}).waitFor();

 await page.getByRole('button',{name:'Favoriten',exact:true}).click();assert.equal(await page.locator('.game-tile').count(),0);
 await page.getByRole('button',{name:'Alle Spiele',exact:true}).click();assert.equal(await page.locator('.game-tile').count(),8);
 await page.getByRole('textbox',{name:'Spiele suchen'}).fill('jurassic');assert.equal(await page.locator('.game-tile').count(),1);
 await page.getByRole('textbox',{name:'Spiele suchen'}).fill('');
 await page.getByRole('button',{name:'Meine Guns',exact:true}).click();
 await page.getByRole('button',{name:'Einrichtung & Prüfung',exact:true}).click();
 await page.getByRole('button',{name:'Zieltest',exact:true}).first().click();
 for(let i=1;i<=5;i++)await page.getByRole('button',{name:'Ziel '+i,exact:true}).click();
 await page.getByRole('heading',{name:'Bedienprobe abgeschlossen.',exact:true}).waitFor();
 await page.getByRole('button',{name:'Zurück zu meinen Guns',exact:true}).click();
 await page.getByRole('button',{name:'Spiele finden',exact:true}).click();await page.getByRole('button',{name:/TeknoParrot Vorhandene/}).click();
 await page.getByRole('status').filter({hasText:'Diese Funktion arbeitet'}).waitFor();
 for(const width of [1440,1024,768,390,320]){
  await page.setViewportSize({width,height:1000});
  for(const section of ['Spielen','Meine Guns','Spiele finden','Einstellungen']){
   await page.getByRole('button',{name:section,exact:true}).click();
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
   assert.equal(overflow,false,section+' overflow at '+width);
  }
 }
 const native=await browser.newPage({viewport:{width:1440,height:1000}});native.on('pageerror',e=>errors.push(e.message));
 await native.addInitScript(()=>{
  const listeners=[];window.fixture={sent:[],emit:(type,payload)=>listeners.forEach(fn=>fn({data:{type,payload}}))};
  window.chrome={webview:{addEventListener:(name,fn)=>listeners.push(fn),removeEventListener:()=>{},postMessage:message=>{
   window.fixture.sent.push(message);if(message.type==='ready')setTimeout(()=>window.fixture.emit('state',{native:true,version:'fixture',games:[],bindings:[{player:1,mouseId:'gun-1',keyboardId:'key-1',serialPort:'COM3',systemId:'rs3',physicalId:'physical-1',softwareConfigured:true}],guns:[{id:'physical-1',name:'3A-3H Retro Shooter 1',systemId:'rs3',mouseId:'gun-1',keyboardId:'key-1',port:'COM3',inputIds:['gun-1','key-1'],driverHealthy:true,issues:[],identityEvidence:'Fixture container'}],devices:[{id:'gun-1',name:'Fixture gun',kind:'mouse',retroShooter:true}],ports:[],settings:{fullscreen:true,startWithWindows:false,hasCoverKey:false,language:'de'},bindingStage:null,installations:[],remoteSession:false}),0);
  }}};
 });
 await native.goto(url);await native.getByRole('button',{name:'Lightguns einrichten'}).waitFor();
 const clickRaw=async(name)=>{
  const box=await native.getByRole('button',{name,exact:true}).boundingBox();assert(box);
  await native.evaluate(({x,y})=>window.fixture.emit('input',{deviceId:'gun-1',kind:'mouse',player:1,x:x/window.innerWidth,y:y/window.innerHeight,buttons:1}),{x:box.x+box.width/2,y:box.y+box.height/2});
 };
 await clickRaw('Einstellungen');
 await native.getByRole('button',{name:'English',exact:true}).evaluate(b=>b.click());
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='set-language'&&m.payload.language==='en')),'Native language switch requests persisted English');
 await native.getByRole('button',{name:'My Guns',exact:true}).waitFor();
 await native.evaluate(()=>window.fixture.emit('notice',{message:'Gun meldet P2. Die Oberfläche unterstützt aktuell P1/P2.'}));
 await native.getByRole('status').filter({hasText:'Gun reports P2.'}).waitFor();
 await native.getByRole('button',{name:'Deutsch',exact:true}).evaluate(b=>b.click());
 await native.getByRole('status').filter({hasText:'Gun meldet P2.'}).waitFor();
 await clickRaw('Meine Guns');await native.getByRole('heading',{name:'Deine Gun. Dein Setup.'}).waitFor();
 await native.evaluate(()=>window.fixture.emit('gun-input',{player:1,token:'mouse:1',down:true,action:'shoot'}));
 await native.waitForFunction(()=>document.querySelector('.gun-hotspot.pressed'));
 await native.evaluate(()=>window.fixture.emit('gun-input',{player:1,token:'mouse:1',down:false,action:'shoot'}));
 await native.waitForFunction(()=>!document.querySelector('.gun-hotspot.pressed'));
 await native.getByRole('button',{name:'Einrichtung & Prüfung',exact:true}).evaluate(b=>b.click());
 await native.getByRole('button',{name:'Zieltest',exact:true}).first().evaluate(b=>b.click());
 // An unassigned mouse / the other player's gun cannot certify this player's target test.
 await native.evaluate(()=>window.fixture.emit('input',{deviceId:'other',kind:'mouse',player:2,x:.5,y:.5,buttons:1}));
 await native.getByText('0 / 5 Ziele · 0 Fehlschüsse', {exact:true}).waitFor();
 const positions=[[.5,.5],[.12,.16],[.88,.84],[.88,.16],[.12,.84]];
 for(const [x,y]of positions){await native.evaluate(({x,y})=>window.fixture.emit('input',{deviceId:'gun-1',kind:'mouse',player:1,x,y,buttons:1}),{x,y});await native.waitForTimeout(40);}
 await native.getByRole('heading',{name:'Eingabetest abgeschlossen.',exact:true}).waitFor();
 await clickRaw('Zurück zu meinen Guns');
 await native.getByRole('dialog',{name:'Zieltest'}).waitFor({state:'hidden'});
 await native.getByRole('button',{name:'Tasten & Live-Eingabe',exact:true}).evaluate(b=>b.click());
 await native.locator('.mapping-row').first().evaluate(b=>b.click());
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='learn-button'&&m.payload.player===1&&m.payload.action==='shoot')),'Physical input learning requests the selected player and action');
 await native.getByRole('button',{name:'Rückstoß & Vibration',exact:true}).evaluate(b=>b.click());
 await native.getByRole('button',{name:'Rückstoß im Test aktivieren'}).evaluate(b=>b.click());
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='set-gun-feedback'&&m.payload.feedback.recoil===false)),'Feedback toggle persists actual test selection');
 await native.evaluate(()=>window.fixture.emit('picker',{title:'Ordner wählen',foldersOnly:true,page:{path:'C:/Arcade',parent:'C:/',entries:[{name:'TeknoParrot',path:'C:/Arcade/TeknoParrot',directory:true}],warning:null},shortcuts:[{name:'C:',path:'C:/'}]}));
 await native.waitForTimeout(350);
 await clickRaw('Diesen Ordner verwenden');
 await native.waitForTimeout(100);
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='choose-path'&&m.payload.path==='C:/Arcade')),'Gun selects actual folder through full-screen picker');
 await native.evaluate(()=>window.fixture.emit('picker',{closed:true}));
 await clickRaw('Einstellungen');
 await native.getByRole('textbox',{name:'SteamGridDB API Schlüssel'}).focus();
 await native.getByRole('dialog',{name:'Cover-Schlüssel eingeben'}).waitFor();
 await clickRaw('a');await clickRaw('b');await clickRaw('Übernehmen');
 assert.equal(await native.getByRole('textbox',{name:'SteamGridDB API Schlüssel'}).inputValue(),'ab','Gun keyboard enters cover key without physical keyboard');
 await native.evaluate(()=>window.fixture.emit('state',{native:true,remoteSession:true,installations:[],version:'remote fixture',games:[],bindings:[],devices:[],ports:[],settings:{fullscreen:true,startWithWindows:false,hasCoverKey:false,language:'de'},bindingStage:null}));
 await native.getByRole('button',{name:'Spiele finden',exact:true}).click();
 await native.getByRole('button',{name:'Installationen automatisch finden',exact:true}).click();
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='scan-installations')),'Remote mouse remains functional without raw input');
 await native.evaluate(()=>window.fixture.emit('import-result',{count:0,warnings:[],validation:true}));
 await native.getByRole('heading',{name:'0 Spiele mit vorhandenen Startdateien.'}).waitFor();
 await native.getByText('BIBLIOTHEK GEPRÜFT',{exact:true}).waitFor();
 const handoffPath=process.env.REAPER_HANDOFF_CHECK;
 if(handoffPath){
  const {readFileSync}=require('node:fs');
  const imported=JSON.parse(readFileSync(handoffPath)).games;
  assert.equal(imported.length,183);
  await native.evaluate(()=>{window.mediaDiagnostic=[];document.addEventListener('error',e=>{if(e.target instanceof HTMLVideoElement)window.mediaDiagnostic.push({code:e.target.error?.code,message:e.target.error?.message,src:e.target.currentSrc});},true);});
  native.on('requestfailed',r=>{if(r.url().includes('fixture.mp4'))console.log('Video network:',r.failure());});
  const first={...imported[0],status:'unverified',setupIssues:[],previewVideo:'http://127.0.0.1:5199/fixture.mp4'};
  await native.route('http://127.0.0.1:5199/fixture.mp4',route=>route.fulfill({contentType:'video/mp4',body:readFileSync(process.env.REAPER_VIDEO_FIXTURE)}));
  await native.getByRole('button',{name:'Zur Bibliothek',exact:false}).click();
  await native.evaluate(games=>window.fixture.emit('state',{native:true,remoteSession:false,installations:[],version:'0.3 fixture',games,bindings:[],devices:[],ports:[],settings:{fullscreen:true,startWithWindows:false,hasCoverKey:false,language:'de'},bindingStage:null}),[first,...imported.slice(1)]);
  await native.waitForFunction(()=>document.querySelector('video')?.currentTime>.1,{},{timeout:5000}).catch(async e=>{console.log('Media diagnostic:',await native.evaluate(()=>({video:document.querySelector('video')?.outerHTML, caption:document.querySelector('.video-caption')?.textContent, codecs:document.createElement('video').canPlayType('video/mp4; codecs="avc1.42E01E"'), errors:window.mediaDiagnostic, tiles:document.querySelectorAll('.game-tile').length, heading:document.querySelector('.hero h1')?.textContent})));throw e;});
  assert.equal(await native.locator('.game-tile').count(),183,'All selected games remain visible');
  await clickRaw('Vorschau pausieren');
  await native.waitForFunction(()=>document.querySelector('video')?.paused===true);
  assert(await native.locator('video').evaluate(v=>v.paused),'Preview can be paused');
  await clickRaw('Vorschau abspielen');
  await native.waitForFunction(()=>document.querySelector('video')?.paused===false);
  await clickRaw('Spieldetails');
  await native.waitForFunction(()=>document.querySelector('video')?.paused===true);
  assert(await native.locator('video').evaluate(v=>v.paused),'Dialog pauses preview');
  await clickRaw('Dialog schließen');
  await native.waitForFunction(()=>document.querySelector('video')?.paused===false);
  await native.evaluate(()=>window.fixture.emit('session',{status:'running'}));
  await native.waitForFunction(()=>document.querySelector('video')?.paused===true);
  assert(await native.locator('video').evaluate(v=>v.paused),'Actual session message pauses preview');
  await native.evaluate(()=>window.fixture.emit('session',{status:'ended'}));
  await clickRaw('Erste Auswahl');
  assert.equal(await native.locator('.game-tile').count(),25,'Priority filter preserves all 25 first choices');
  await clickRaw('Alle Spiele');
  await native.getByLabel('System filtern').selectOption('Nintendo Wii');
  assert.equal(await native.locator('.game-tile').count(),9,'Actual Wii system filter');
  await native.getByLabel('System filtern').selectOption('all');
  await clickRaw('Dateien vorhanden');
  assert.equal(await native.locator('.game-tile').count(),1,'Unavailable migrated games cannot appear file ready');
  await clickRaw('Spiele finden');
  assert.equal(await native.locator('video').count(),0,'View change removes the video player');
  await clickRaw('Übergabepaket importieren');
  assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='import-collection')),'Native handoff import is connected');
  console.log('Collection UI passed: 183 games, 25 priorities, 9 Wii games, missing-file filter, real MP4 playback and pause on dialog/session/view change.');
 }
 await native.evaluate(()=>window.fixture.emit('session',{status:'running'}));
 await native.getByRole('button',{name:'Spielmenü öffnen',exact:true}).dispatchEvent('click');
 assert(await native.evaluate(()=>window.fixture.sent.some(m=>m.type==='show-overlay')),'Running session offers the native game overlay command');
 await native.evaluate(()=>window.fixture.emit('session',{status:'ended'}));
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('UI passed: empty-library honesty, eight preview entries, selection/filter/search, target test, browser-native boundary, raw-input navigation, player isolation, binding command, four pages at five widths.');
 await browser.close();
})();
