using System.Net;
using System.Text;
using System.Xml.Linq;
using Reaper.Core;

int checks = 0;
var emergency = new EmergencyChord();
Check(!emergency.Sample(true,true,0) && !emergency.Sample(true,true,1999) && emergency.Sample(true,true,2000), "Dedicated Start+Coin exit uses a monotonic two-second hold");
Check(!emergency.Sample(true,true,5000) && !emergency.Sample(false,true,6000) && !emergency.Sample(true,true,9000), "Held exit chord cannot fire again or rearm after releasing only one button");
emergency.Sample(false,false,10000);
Check(!emergency.Sample(true,true,11000) && emergency.Sample(true,true,13000), "Both buttons must be released before another emergency exit");
var interrupted = new EmergencyChord(); interrupted.Sample(true,true,0); interrupted.Sample(true,false,1900);
Check(!interrupted.Sample(true,true,2000) && !interrupted.Sample(true,true,3900) && interrupted.Sample(true,true,4000), "Releasing Coin cancels a partial emergency hold");
var pulseHold = new TriggerHold(); var independent = new EmergencyChord(); bool fired=false;
for(long t=0;t<=12000;t+=20) { pulseHold.Button("MG", t%80<40,t); fired |= independent.Sample(true,true,t); }
Check(!pulseHold.Ready(12000) && fired,"Autofire release pulses prevent the old trigger hold but cannot reset the dedicated exit chord");
Check(DesktopAim.Position(0,65535,-1920,-1080,3840,2160)==(-1920,1079),"Desktop aim maps normalized coordinates to the virtual desktop including negative origins");
Check(DesktopAim.Position(65535,0,0,0,1920,1080)==(1919,0) && DesktopAim.Position(-1,0,0,0,1920,1080) is null,"Desktop aim reaches exact screen edges and rejects malformed coordinates");
GunBinding desktopP1=new(1,"gun-one"),desktopP2=new(2,"gun-two");
Check(DesktopAim.Binding([desktopP1,desktopP2],"GUN-TWO")?.Player==2 && DesktopAim.Binding([desktopP1,desktopP2],"rdp-mouse") is null,"Desktop markers route only the assigned physical mouse and keep P1/P2 distinct");
Check(DesktopAim.Binding([desktopP1,desktopP2 with {MouseId="gun-one"}],"gun-one") is null,"Ambiguous duplicate devices cannot appear as two independent cursors");
var gunAim=new GunAim();gunAim.Remember("P1",true,12000,20000,false);gunAim.Remember("P2",true,52000,43000,true);
gunAim.Remember("P2",false,0,0,false);
Check(gunAim.TryGet("p2",out var p2Aim) && p2Aim==new GunAim.Position(52000,43000,true) && gunAim.TryGet("P1",out var p1Aim) && p1Aim.X==12000,"Button-only packets keep each gun's independent aim instead of the shared desktop cursor");
gunAim.RetainDevices(new(StringComparer.OrdinalIgnoreCase){"p1"});
Check(!gunAim.TryGet("P2",out _) && gunAim.TryGet("P1",out _),"Disconnecting a gun removes its stale aim while retaining the other player's position");

Check(I18n.Language == "en" && new AppSettings().Language == "en", "English is the default UI and settings language");
Check(System.Text.Json.JsonSerializer.Deserialize<AppSettings>("{}", JsonDefaults.Options)!.Language == "en", "Libraries without a language migrate to English");
I18n.Language = "en";
Check(I18n.T("Neu starten") == "Restart game" && I18n.F($"Gun meldet P{2}. Die Oberfläche unterstützt aktuell P1/P2.") == "Gun reports P2. The interface currently supports P1/P2.", "Native menu and formatted device errors use the English catalog");
Check(I18n.Normalize("fr") == "en" && I18n.Normalize("de") == "de", "Unsupported language values fall back to English");
I18n.Language = "de";
Check(I18n.T("Neu starten") == "Neu starten" && OverlayControls.ActionName("coin") == "Münze", "Switching to German updates native controls immediately");
var languageStore = new LibraryStore(Path.Combine(Path.GetTempPath(), "reaper-language-" + Guid.NewGuid()));
var languageLibrary = LibraryState.Empty with { Settings = new AppSettings(Language: "de") };
languageStore.Save(languageLibrary);
Check(languageStore.Load().Settings.Language == "de" && !languageStore.Load().Settings.StartWithWindows, "German language survives a cold reload without changing autostart");
Directory.Delete(languageStore.DirectoryPath, true);
// Existing profile assertions use the German catalog.
void Check(bool pass, string label) { if (!pass) throw new Exception("FAIL: " + label); checks++; Console.WriteLine("PASS: " + label); }
void Throws(Action action, string label) { try { action(); throw new Exception("Expected error: " + label); } catch (Exception e) when (!e.Message.StartsWith("Expected error")) { checks++; Console.WriteLine("PASS: " + label); } }
string root = Path.Combine(args.FirstOrDefault() ?? Path.GetTempPath(), "reaper-check-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
try
{
    var healthGame=new GameEntry("check-fixture","Fixture","PC","fixture.exe",[],root,"custom","fixture");
    string healthFile=Path.Combine(root,"game-test-check-fixture.json");
    File.WriteAllText(healthFile,"{\"id\":\"check-fixture\",\"windowObserved\":true,\"gameWindowAvailable\":true,\"ended\":true,\"processesAfterExit\":[],\"error\":null}");
    Check(GameLaunchCheck.Read(healthGame,root)?.Title=="Start und Beenden geprüft" && GameLaunchCheck.Read(healthGame,root)!.Notes.Any(n=>n.Contains("kein vollständiger Spieltest")),"A clean observed launch is shown as launch/exit evidence, never complete physical gameplay");
    File.WriteAllText(healthFile,"{\"id\":\"check-fixture\",\"windowObserved\":true,\"gameWindowAvailable\":true,\"ended\":true,\"processesAfterExit\":[42],\"error\":null}");
    Check(GameLaunchCheck.Read(healthGame,root)?.Title=="Startprüfung benötigt Aufmerksamkeit","A leftover owned process prevents a successful session-cleanup label");
    File.WriteAllText(healthFile,"{\"id\":\"different-game\",\"windowObserved\":true,\"gameWindowAvailable\":true,\"ended\":true}");
    Check(GameLaunchCheck.Read(healthGame,root) is null,"Another game's launch report cannot confirm this game");
    string multiRoot=Path.Combine(root,"multiplayer");Directory.CreateDirectory(multiRoot);
    string helperExe=Path.Combine(multiRoot,"DemulShooterX64.exe");File.WriteAllText(helperExe,"");
    string multiConfig=Path.Combine(multiRoot,"config.ini");File.WriteAllText(multiConfig,";user custom config\r\nP1DeviceName = old-one\r\nP2DeviceName = old-two\r\nP2DeviceName = duplicate\r\nOutputEnabled = True\r\n");
    var multiGame=new GameEntry("multi","Operation Wolf Returns","PC",helperExe,[],multiRoot,"custom",multiRoot,Helpers:[new(helperExe,["-target=windows","-rom=opwolfr"],multiRoot)]);
    GunBinding p1=new(1,@"\\?\HID#VID_0483&PID_5750&MI_00&COL01#p1",SystemId:"rs3");
    GunBinding p2=new(2,@"\\?\HID#VID_0483&PID_5751&MI_00&COL01#p2",SystemId:"rs3");
    string rpcRoot=Path.Combine(root,"rpcs3");Directory.CreateDirectory(rpcRoot);
    string rpcExe=Path.Combine(rpcRoot,"rpcs3.exe");File.WriteAllText(rpcExe,"fixture Raw Mouse capability");
    File.WriteAllText(Path.Combine(rpcRoot,"config.yml"),"Video:\n  Renderer: Vulkan\n  Vulkan:\n    Adapter: Foreign GPU\n    Force FIFO present mode: true\nCore:\n  PPU Threads: 2\n");
    var rpcGame=multiGame with {Executable=rpcExe,WorkingDirectory=rpcRoot};
    var rpcPrepared=Rpcs3Setup.Configure(rpcGame,[p1,p2]);
    string rpcRaw=File.ReadAllText(Path.Combine(rpcRoot,"config","raw_mouse.yml")),rpcCfg=File.ReadAllText(Path.Combine(rpcRoot,"config.yml"));
    Check(Rpcs3Setup.YamlValue(rpcRaw,["Player 2"],"Device")==p2.MouseId && Rpcs3Setup.YamlValue(rpcRaw,["Player 1"],"Device")==p1.MouseId,"RPCS3 round-trips exact individual raw mouse identities including escaped Windows paths");
    Check(Rpcs3Setup.EncodeKey(49)==131072 && Rpcs3Setup.EncodeKey(38)==21495808 && Rpcs3Setup.YamlValue(rpcRaw,["Player 2"],"Button 6")=="Key 196608","RPCS3 encodes scan codes in the high word, including extended arrows, rather than writing virtual keys");
    Check(rpcCfg.Contains("Force FIFO present mode: true") && rpcCfg.Contains("PPU Threads: 2") && Rpcs3Setup.YamlValue(rpcCfg,["Video","Vulkan"],"Adapter")=="" && rpcPrepared.Arguments.Contains("--no-gui"),"RPCS3 preserves unrelated graphics/CPU overrides and clears only a stale GPU choice while booting directly");
    Check(!File.Exists(Path.Combine(rpcRoot,"raw_mouse.yml")) && File.Exists(Path.Combine(rpcRoot,"config","gem_mouse.yml")),"RPCS3 input profiles are written to its Windows config subdirectory, rather than an ignored root file");
    var rpcLegend=OverlayControls.Read(rpcGame,root,[p1,p2]);
    Check(StartupControls.ForPlayer(rpcLegend,p2).Any(h=>h.ControlIds.Contains("trigger")&&h.Resolved) && StartupControls.ForPlayer(rpcLegend,p2).Any(h=>h.ControlIds.Contains("coin")&&h.Resolved),"RPCS3 legend reads active Move actions through raw bindings to the real P2 gun controls");
    Rpcs3Setup.Configure(rpcGame,[p1]);rpcRaw=File.ReadAllText(Path.Combine(rpcRoot,"config","raw_mouse.yml"));
    Check(Rpcs3Setup.YamlValue(rpcRaw,["Player 2"],"Device")=="" && OverlayControls.Read(rpcGame,root,[p2]).Rows.Length==0,"Disconnected RPCS3 P2 is cleared and its legend cannot claim a working mapping");
    File.WriteAllText(rpcExe,"older unsupported emulator");
    Check(Rpcs3Setup.Configure(rpcGame,[p1,p2])==rpcGame && File.ReadAllText(Path.Combine(rpcRoot,"config","raw_mouse.yml"))==rpcRaw,"Older RPCS3 builds remain unchanged until their Raw Mouse backend is available");
    string raRoot = Path.Combine(root,"retroarch"); Directory.CreateDirectory(raRoot);
    await using(var bridge=new DolphinGunBridge([p1 with{KeyboardId="kb1"},p2 with{KeyboardId="kb2"}]))
    {
        bridge.Mouse(p1.MouseId,true,12345,54321,1);bridge.Mouse(p2.MouseId,true,60000,6000,0);bridge.Key("kb2",50,true);
        var frame1=bridge.Frame(1);var frame2=bridge.Frame(2);
        double nativeX=-System.Buffers.Binary.BinaryPrimitives.ReadSingleLittleEndian(frame1.AsSpan(76))*9.80665;
        Check(Math.Abs(nativeX-(12345/65535.0*2-1))<0.000001 && frame1[55]==255 && frame2[55]==0 && (frame2[36]&8)!=0,"Dolphin bridge preserves float absolute aim and separates P1 trigger from P2 Start");
        uint frameCrc=System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(frame1.AsSpan(8));frame1.AsSpan(8,4).Clear();
        Check(DolphinGunBridge.Crc(frame1)==frameCrc && DolphinGunBridge.Crc("123456789"u8)==0xcbf43926,"Dolphin DSU messages carry the native protocol length and valid CRC32");
        bridge.Mouse(p1.MouseId,false,0,0,2);bridge.Pause(true);
        Check(bridge.Frame(1)[55]==0 && bridge.Frame(2)[36]==0,"Gun release packets and the overlay pause cannot leave trigger/Start stuck in Dolphin");
        using var nativeClient=new System.Net.Sockets.UdpClient(new IPEndPoint(IPAddress.Loopback,0));
        byte[] request=new byte[28];"DSUC"u8.CopyTo(request);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(request.AsSpan(4),1001);System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(request.AsSpan(6),12);
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(request.AsSpan(16),0x100001);System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(request.AsSpan(20),2);request[24]=0;request[25]=1;
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(request.AsSpan(8),DolphinGunBridge.Crc(request));
        await nativeClient.SendAsync(request,new IPEndPoint(IPAddress.Loopback,bridge.Port));
        var port1=await nativeClient.ReceiveAsync().WaitAsync(TimeSpan.FromSeconds(2));var port2=await nativeClient.ReceiveAsync().WaitAsync(TimeSpan.FromSeconds(2));
        Check(port1.Buffer.Length==32&&port1.Buffer[20]==0&&port1.Buffer[21]==2&&port2.Buffer[20]==1&&port2.Buffer[21]==2,"Dolphin's actual loopback discovery requests receive two independent connected gun ports");
        request.AsSpan(8,4).Clear();System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(request.AsSpan(16),0x100002);request.AsSpan(20,8).Clear();request[20]=1;request[21]=1;
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(request.AsSpan(8),DolphinGunBridge.Crc(request));
        await nativeClient.SendAsync(request,new IPEndPoint(IPAddress.Loopback,bridge.Port));var liveFrame=await nativeClient.ReceiveAsync().WaitAsync(TimeSpan.FromSeconds(2));
        Check(liveFrame.Buffer.Length==100&&liveFrame.Buffer[20]==1,"Dolphin's native P2 subscription receives live P2 frames over UDP");
    }
    var raGame = multiGame with { Id="ra-test", Executable=Path.Combine(raRoot,"retroarch.exe"), WorkingDirectory=raRoot, Arguments=["-L","cores/mednafen_psx_libretro.dll","disc.chd","--appendconfig","custom.cfg"] };
    var raPrepared = RetroArchSetup.Configure(raGame,root,[p1,p2],["", "RDP",p2.MouseId,p1.MouseId]);
    string raText=File.ReadAllText(RetroArchSetup.ProfilePath(raGame,root));
    Check(raText.Contains("input_player1_mouse_index = \"3\"") && raText.Contains("input_player2_mouse_index = \"2\"") && raText.Contains("input_libretro_device_p1 = \"260\""),"RetroArch uses actual zero-based RawInput order including unnamed/RDP devices and Guncon ports");
    Check(raPrepared.Arguments.Count(a=>a=="--appendconfig")==1 && raPrepared.Arguments.Last().StartsWith("custom.cfg|") && raText.Contains("input_player2_gun_start = \"num2\"") && raText.Contains("input_enable_hotkey = \"f11\""),"RetroArch preserves explicit overrides and separates gun Start/Coin from emulator hotkeys");
    var preparedRaControls=OverlayControls.Read(raGame,root,[p1,p2]);
    Check(StartupControls.ForPlayer(preparedRaControls,p2).Any(h=>h.Resolved && h.ControlIds.Contains("trigger")) && StartupControls.KeyToken("num2")=="key:50","RetroArch launch legend resolves actual P2 mouse buttons and numeric keys");
    RetroArchSetup.Configure(raGame,root,[p1],["RDP",p1.MouseId,p2.MouseId]);
    Check(File.ReadAllText(RetroArchSetup.ProfilePath(raGame,root)).Contains("input_libretro_device_p2 = \"0\""),"Disconnected RetroArch P2 cannot inherit the P1/RDP mouse");
    var nesGame=raGame with { Id="nes-test", Arguments=["-L","cores/fceumm_libretro.dll","duckhunt.zip"] };
    RetroArchSetup.Configure(nesGame,root,[p1,p2],[p2.MouseId,p1.MouseId]);
    string nesText=File.ReadAllText(RetroArchSetup.ProfilePath(nesGame,root));
    Check(nesText.Contains("input_libretro_device_p2 = \"258\"") && nesText.Contains("input_player2_mouse_index = \"1\"") && nesText.Contains("deadeye_player2_physical = \"1\""),"NES Zapper uses original hardware port 2 while the gun and legend remain physical P1");
    string flycastRoot=Path.Combine(root,"flycast");Directory.CreateDirectory(flycastRoot);
    var flycastGame=multiGame with {Executable=Path.Combine(flycastRoot,"flycast.exe"),WorkingDirectory=flycastRoot};
    var flyP1=p1 with {KeyboardId=p1.MouseId.Replace("COL01","COL02")};
    var flyP2=p2 with {KeyboardId=p2.MouseId.Replace("COL01","COL02")};
    InputDevice[] flyDevices=[new(flyP2.MouseId,"P2","mouse",true),new(flyP1.MouseId,"P1","mouse",true),new(flyP1.KeyboardId!,"P1 keyboard","keyboard",true),new(flyP2.KeyboardId!,"P2 keyboard","keyboard",true),new(@"\\?\Root#RDP_MOU","Remote","mouse",false)];
    var flyNames=flyDevices.ToDictionary(d=>d.Id,d=>d.Kind=="keyboard"?"HID Keyboard Device":"HID-compliant mouse");
    FlycastSetup.Configure(flycastGame,[flyP1,flyP2],flyDevices,flyNames);
    string flyText=File.ReadAllText(Path.Combine(flycastRoot,"emu.cfg"));
    Check(DolphinSetup.Value(flyText,"input","maple_"+FlycastSetup.DeviceId(flyP1.MouseId,"mouse"))=="0" && DolphinSetup.Value(flyText,"input","maple_"+FlycastSetup.DeviceId(flyP2.MouseId,"mouse"))=="1","Flycast pins actual P1/P2 USB paths independently of enumeration order");
    Check(DolphinSetup.Value(flyText,"input","maple_"+FlycastSetup.DeviceId(@"\\?\Root#RDP_MOU","mouse"))=="-1","Flycast excludes the remote desktop mouse from both player ports");
    string flyKeyboard=Directory.GetFiles(Path.Combine(flycastRoot,"mappings"),"*5751*arcade.cfg").Single();
    Check(File.ReadAllText(flyKeyboard).Contains("31:btn_start") && File.ReadAllText(flyKeyboard).Contains("35:btn_d") && !File.ReadAllText(flyKeyboard).Contains("btn_fforward"),"Flycast P2 Start/Coin use its factory USB keys and gun buttons cannot trigger fast-forward");
    FlycastSetup.Configure(flycastGame,[flyP1],flyDevices,flyNames);
    Check(DolphinSetup.Value(File.ReadAllText(Path.Combine(flycastRoot,"emu.cfg")),"input","device2")=="10" && DolphinSetup.Value(File.ReadAllText(Path.Combine(flycastRoot,"emu.cfg")),"input","maple_"+FlycastSetup.DeviceId(flyP2.MouseId,"mouse"))=="-1","Disconnecting P2 disables its Flycast port rather than assigning a foreign mouse");
    MultiplayerSetup.Configure(multiGame,[p1,p2]);
    Check(File.ReadAllText(multiConfig).Contains(p1.MouseId)&&File.ReadAllText(multiConfig).Contains(p2.MouseId)&&File.ReadAllText(multiConfig).Contains("OutputEnabled = True"),"Live independent P1/P2 IDs replace foreign helper assignments and preserve custom settings");
    Check(File.ReadAllText(multiConfig+".before-deadeye-multiplayer").Contains("old-two"),"Original helper configuration remains recoverable");
    MultiplayerSetup.Configure(multiGame,[p1]);
    Check(File.ReadAllText(multiConfig).Contains("P2DeviceName = DEADEYE_DISCONNECTED_P2")&&!File.ReadAllText(multiConfig).Contains(p2.MouseId),"Unplugged P2 cannot inherit an unrelated gun assignment");
    Check(File.ReadAllText(multiConfig).Contains("P3DeviceName = DEADEYE_DISCONNECTED_P3")&&File.ReadAllText(multiConfig).Contains("P4DeviceName = DEADEYE_DISCONNECTED_P4"),"Unused channels cannot bind to nameless RDP mouse input");
    File.WriteAllText(Path.Combine(multiRoot,"EMULATOR.INI"),"[Input]\nUseRawInput=1\n[Renderer]\nDrawCross=1\nBilinear=1\n");
    var multiplayerModelGame=multiGame with { Helpers=[new(helperExe,["-target=model2","-rom=hotd"],multiRoot)] };
    MultiplayerSetup.Configure(multiplayerModelGame,[p1,p2]);
    Check(DolphinSetup.Value(File.ReadAllText(Path.Combine(multiRoot,"EMULATOR.INI")),"Input","UseRawInput")=="0"&&DolphinSetup.Value(File.ReadAllText(Path.Combine(multiRoot,"EMULATOR.INI")),"Renderer","DrawCross")=="0"&&File.ReadAllText(Path.Combine(multiRoot,"EMULATOR.INI")).Contains("Bilinear=1"),"Model2 helper prevents conflicting native input without changing renderer preferences");
    Throws(()=>MultiplayerSetup.Configure(multiGame,[p1,p2 with {MouseId=p1.MouseId}]),"One mouse cannot masquerade as two independent players");
    File.WriteAllText(Path.Combine(multiRoot,"BlueEstate_Fix.dll"),"");
    var blueGame=multiGame with {Title="Blue Estate",Helpers=null};
    MultiplayerSetup.Configure(blueGame,[p1,p2]);
    Check(DolphinSetup.Value(File.ReadAllText(Path.Combine(multiRoot,"LightGun_Patch.ini")),"LightGuns","Gun2")=="VID_0483&PID_5751","Blue Estate receives the real distinct P2 VID/PID");
    Throws(()=>MultiplayerSetup.Configure(blueGame,[p1,p2 with {MouseId=p1.MouseId+"other"}]),"Blue Estate rejects distinct paths with the same VID/PID");
    var hotd2=multiGame with {Title="THE HOUSE OF THE DEAD 2: Remake",Helpers=null};
    string hotd2Assignment=Path.Combine(multiRoot,"lightgun_config.ini");
    File.WriteAllText(hotd2Assignment,"# retained\nPlayer1Gun=old\nPlayer1Gun = duplicate\n");
    MultiplayerSetup.WriteCompactGunAssignments(hotd2Assignment,[p1,p2]);
    string hotd2Text=File.ReadAllText(hotd2Assignment);
    Check(hotd2Text.Split('\n').Count(l=>l.StartsWith("Player1Gun="))==1 && hotd2Text.Contains("Player2Gun=VID_0483&PID_5751") && !hotd2Text.Contains("Player1Gun ="),"HOTD 2 plugin's literal prefix parser receives exact compact P1/P2 assignments without duplicate keys");
    Check(File.ReadAllText(hotd2Assignment+".before-deadeye-multiplayer").Contains("Player1Gun=old") && hotd2Text.Contains("# retained"),"HOTD 2 assignment repair preserves the original config and unrelated lines");
    Throws(()=>MultiplayerSetup.WriteCompactGunAssignments(hotd2Assignment,[p1,p2 with {MouseId=p1.MouseId+"other"}]),"HOTD 2 VID/PID assignment rejects two paths sharing one device pair");
    Check(!MultiplayerSetup.ConfigureHouseDead2Remake(hotd2,[p1,p2]),"Unknown or absent HOTD 2 plugin versions retain their manual setup");
    var hotd2Controls=MultiplayerSetup.ReadCompactGunAssignments(hotd2Assignment,[p1,p2]);
    Check(hotd2Controls.Rows.Count(r=>r.Player==2)==3 && StartupControls.ForPlayer(hotd2Controls,p2).All(r=>r.Resolved),"HOTD 2's actual plugin assignment resolves P2 trigger, grip reload and magazine reload on its own gun");
    Check(MultiplayerSetup.ReadCompactGunAssignments(hotd2Assignment,[p2 with {MouseId=p1.MouseId}]).Rows.Length==0,"HOTD 2 legend does not claim a P2 assignment belonging to another device");
    Check(GameCompatibility.Read(hotd2,1)!.Notes.Any(n=>n.Contains("MultiLightgunPlugin"))&&!GameCompatibility.Read(hotd2,1)!.Notes.Any(n=>n.Contains("-rom=hotdra")),"HOTD 2 Remake never inherits the incompatible HOTD 1 helper recipe");
    string tp = Path.Combine(root, "TeknoParrot"); Directory.CreateDirectory(Path.Combine(tp, "UserProfiles")); Directory.CreateDirectory(Path.Combine(tp, "GameProfiles"));
    File.WriteAllText(Path.Combine(tp, "TeknoParrotUi.exe"), ""); File.WriteAllText(Path.Combine(tp, "game & 1.exe"), "");
    File.WriteAllText(Path.Combine(tp, "GameProfiles", "HOTDSD.xml"), "<GameProfile/>");
    File.WriteAllText(Path.Combine(tp, "UserProfiles", "HOTDSD.xml"), "<GameProfile><GamePath>game &amp; 1.exe</GamePath></GameProfile>");
    File.WriteAllText(Path.Combine(tp, "UserProfiles", "MarioKart.xml"), "<GameProfile><GamePath>game &amp; 1.exe</GamePath></GameProfile>");
    File.WriteAllText(Path.Combine(tp, "UserProfiles", "TC5.xml"), "<GameProfile><GamePath>missing.exe</GamePath></GameProfile>");
    File.WriteAllText(Path.Combine(tp, "UserProfiles", "HOTD4.xml"), "<broken>");
    var import = GameImporter.TeknoParrot(tp);
    Check(import.Games.Count == 2, "TeknoParrot imports gun profiles, excludes racer and broken XML");
    var scarlet = import.Games.Single(g => g.Title.Contains("Scarlet"));
    Check(scarlet.Status == "unverified", "Existing profile is unverified, never falsely tested");
    Check(import.Games.Single(g => g.Title.Contains("Crisis")).Status == "needs-setup", "Missing game file produces needs-setup");
    Check(import.Warnings.Count == 3, "Ignored, incomplete and broken profiles report their cause");
    var launch = LaunchRules.Prepare(scarlet);
    Check(launch.ArgumentList.Single() == "--profile=HOTDSD.xml" && launch.WorkingDirectory == tp, "TeknoParrot uses profile basename and correct working directory");
    Throws(() => LaunchRules.Prepare(import.Games.Single(g => g.Title.Contains("Crisis"))), "Incomplete profile cannot launch");
    Throws(() => LaunchRules.Prepare(scarlet with { Source = "demo" }), "Preview entry cannot launch");
    const string xml = "<!DOCTYPE mame [<!ELEMENT mame ANY>]><mame><machine name='pointblank'><description>Point Blank</description><input><control type='lightgun'/></input></machine><machine name='sf2'><description>Street Fighter II</description><input><control type='joystick'/></input></machine><machine name='area51'><description>Area 51</description><input><control type='lightgun'/></input></machine><machine name='device' isdevice='yes'><input><control type='lightgun'/></input></machine></mame>";
    using var stream = new MemoryStream(Encoding.UTF8.GetBytes(xml)); var catalog = GameImporter.MameGunCatalog(stream);
    Check(catalog.Count == 2 && catalog.ContainsKey("area51"), "MAME streaming parser preserves consecutive machines and excludes non-gun devices");
    string roms = Path.Combine(root, "roms"); Directory.CreateDirectory(roms); File.WriteAllText(Path.Combine(roms, "pointblank.zip"), ""); File.WriteAllText(Path.Combine(roms, "sf2.zip"), "");
    var mame = GameImporter.Mame(scarlet.Executable, roms, catalog);
    Check(mame.Games.Count == 1 && mame.Games[0].Title == "Point Blank", "MAME combines actual ROM files with emulator gun catalog");
    Check(mame.Games[0].Arguments.Contains("-lightgunprovider") && mame.Games[0].Aspect == "4:3", "MAME imports raw-input profile and 4:3 format");
    var state = LibraryState.Empty; LibraryStore.Merge(state, import.Games); var old = state.Games.Single(g => g.Id == scarlet.Id);
    state.Games[state.Games.IndexOf(old)] = old with { Favorite = true, Status = "tested", Cover = "mine.png" };
    LibraryStore.Merge(state, import.Games);
    Check(state.Games.Count == 2 && state.Games.Single(g => g.Id == scarlet.Id).Favorite, "Reimport deduplicates and retains favorite");
    Check(state.Games.Single(g => g.Id == scarlet.Id).Status == "tested" && state.Games.Single(g => g.Id == scarlet.Id).Cover == "mine.png", "Unchanged launch retains user verdict and cover");
    LibraryStore.Merge(state, [scarlet with { Arguments = ["--profile=changed.xml"] }]);
    Check(state.Games.Single(g => g.Id == scarlet.Id).Status == "unverified", "Changed launch invalidates prior playable verdict");
    var store = new LibraryStore(Path.Combine(root, "data")); store.Save(state); store.Save(state); var cold = store.Load();
    Check(cold.Games.Count == 2 && cold.Games.Single(g => g.Id == scarlet.Id).Favorite, "Library survives cold reload");
    Check(File.Exists(Path.Combine(root, "data", "library.json.bak")), "Saving preserves the previous library snapshot");
    File.WriteAllText(Path.Combine(root, "data", "library.json"), "broken"); Throws(() => store.Load(), "Damaged library fails explicitly and is not overwritten");
    string mouse = @"\\?\HID#VID_1234&PID_4321#player1";
    var controller = XDocument.Parse(LaunchRules.MameController([new(1, mouse)]));
    Check(controller.Descendants("mapdevice").Single().Attribute("device")!.Value == mouse, "MAME mapping retains and XML-escapes exact device identity");
    Check(GunSystems.Identify("3A-3H Retro Shooter 1") == "rs3" && GunSystems.Identify("STM32 USB Serial") is null, "Product identity detects the RS3 family without treating generic STM devices as guns");
    Check(GunSystems.Identify("Sinden Lightgun") == "sinden" && GunSystems.Identify("X-Gunner") == "xgunner" && GunSystems.Identify("Blamcon Vyper") == "blamcon", "Known manufacturer product names select their own system adapters");
    Check(GunSystems.DefaultMap(1)["key:38"]=="up" && !GunSystems.DefaultMap(1).ContainsKey("key:85") && GunSystems.DefaultMap(2)["key:85"]=="up", "Reaper factory direction keys differ between P1 and P2");
    Check(GunSystems.DefaultMap(1)["key:81"]=="start" && GunSystems.DefaultMap(2)["key:78"]=="secondary", "Reaper stick press and side key follow the manufacturer PC diagram");
    Check(!GunSystems.DefaultMap(1,"sinden").ContainsKey("key:49"), "Other manufacturers do not inherit Reaper keyboard assumptions");
    string model2=Path.Combine(root,"model2"); Directory.CreateDirectory(model2);
    string model2config=Path.Combine(model2,"EMULATOR.INI"); File.WriteAllText(model2config,"[RomDirs]\nDir1=roms ; existing local path\nDir2=\n[Renderer]\nAutoFull=1\n");
    var model2game=scarlet with { Source="custom",Executable=Path.Combine(model2,"emulator_multicpu.exe"),WorkingDirectory=model2,SourcePath=Path.Combine(roms,"pointblank.zip") };
    Check(EmulatorSetup.ConfigurePaths(model2game)&&File.ReadAllText(model2config).Contains("Dir2="+roms),"Model 2 receives the explicit library ROM folder instead of searching an empty local ROM directory");
    Check(!EmulatorSetup.ConfigurePaths(model2game)&&File.Exists(model2config+".before-reaper-path-fix")&&File.ReadAllText(model2config).Contains("AutoFull=1"),"Model 2 repair is idempotent, backs up its original config and preserves renderer settings");
    Check(!EmulatorSetup.ConfigurePaths(model2game with {Executable=scarlet.Executable}),"ROM path repair does not change unrelated emulators");
    string ps2dir=Path.Combine(root,"portable-ps2"),ps2config=Path.Combine(ps2dir,"inis","PCSX2.ini");Directory.CreateDirectory(Path.GetDirectoryName(ps2config)!);
    var ps2game=model2game with {Executable=Path.Combine(ps2dir,"pcsx2.exe"),WorkingDirectory=ps2dir};
    File.WriteAllText(ps2config,"[Folders]\nMemoryCards = "+Path.Combine(root,"unavailable-drive","cards")+"\nBios = bios\n[USB1]\nType = guncon2\n");
    Check(EmulatorSetup.ConfigurePaths(ps2game)&&Directory.Exists(Path.Combine(ps2dir,"memcards"))&&File.ReadAllText(ps2config).Contains("Type = guncon2"),"PCSX2 repairs unavailable absolute memory-card storage without changing gun inputs");
    Check(!EmulatorSetup.ConfigurePaths(ps2game)&&File.Exists(ps2config+".before-reaper-storage-fix"),"PCSX2 keeps accessible storage and makes one original backup");

    string dualDir=Path.Combine(tp,"DualTitle"),dualMain=Path.Combine(dualDir,"bin","game.exe"),dualSecond=Path.Combine(dualDir,"service","daemon.exe");
    Directory.CreateDirectory(Path.GetDirectoryName(dualMain)!);Directory.CreateDirectory(Path.GetDirectoryName(dualSecond)!);File.WriteAllText(dualMain,"");File.WriteAllText(dualSecond,"");
    string dualProfile=Path.Combine(tp,"UserProfiles","dual.xml");
    File.WriteAllText(dualProfile,new XDocument(new XElement("GameProfile",new XElement("GamePath",dualMain),new XElement("HasTwoExecutables","true"),new XElement("GamePath2",Path.Combine(root,"old-drive","DualTitle","service","daemon.exe")))).ToString());
    var dualGame=scarlet with {SourcePath=dualProfile};
    Check(LaunchRules.Issues(dualGame).Length==1,"Dual executable profiles validate the second launcher rather than falsely reporting file readiness");
    Check(LaunchRules.RepairTeknoParrotPath(dualGame)&&XDocument.Load(dualProfile).Descendants("GamePath2").Single().Value==dualSecond&&!LaunchRules.RepairTeknoParrotPath(dualGame),"Second launcher is rebased through a shared ancestor only when one existing file matches");
    var customGun = new GunBinding(1,mouse,ButtonMap:new(){["key:85"]="coin"});
    Check(GunSystems.UpgradeMap(customGun)["key:85"]=="coin", "Factory migration preserves custom button bindings");
    Check(GunSystems.ValidControl("sinden","pump") && !GunSystems.ValidControl("rs3","pump"), "Physical learning accepts only controls belonging to the selected hardware");
    string repairProfile=Path.Combine(tp,"UserProfiles","repair.xml"); File.WriteAllText(repairProfile,"<GameProfile><GamePath>missing.exe</GamePath><Keep>original</Keep></GameProfile>");
    var repair=scarlet with { SourcePath=repairProfile, RequiredFiles=[repairProfile,Path.Combine(tp,"game & 1.exe")] };
    Check(LaunchRules.RepairTeknoParrotPath(repair) && XDocument.Load(repairProfile).Descendants("GamePath").Single().Value==Path.Combine(tp,"game & 1.exe"), "TeknoParrot repair uses one explicit existing library binary and escapes XML paths");
    Check(File.Exists(repairProfile+".before-reaper-path-fix") && XDocument.Load(repairProfile).Descendants("Keep").Single().Value=="original" && !LaunchRules.RepairTeknoParrotPath(repair), "Profile repair retains all other settings, makes a backup and is idempotent");
    File.WriteAllText(repairProfile,"<GameProfile><GamePath>missing.exe</GamePath></GameProfile>");
    Check(!LaunchRules.RepairTeknoParrotPath(repair with {RequiredFiles=[Path.Combine(tp,"game & 1.exe"),Path.Combine(tp,"TeknoParrotUi.exe")]}), "Ambiguous game files never overwrite a profile");
    File.WriteAllText(repairProfile,"<GameProfile><ConfigValues><FieldInformation><FieldName>Input API</FieldName><FieldValue>XInput</FieldValue><FieldOptions><string>RawInput</string></FieldOptions></FieldInformation></ConfigValues><JoystickButtons><JoystickButtons><ButtonName>Player 1 Light Gun</ButtonName></JoystickButtons><JoystickButtons><ButtonName>Player 1 Gun Trigger</ButtonName></JoystickButtons><JoystickButtons><ButtonName>Player 1 Start</ButtonName></JoystickButtons><JoystickButtons><ButtonName>Player 1 Footpedal</ButtonName><BindName>Keep pedal</BindName></JoystickButtons></JoystickButtons></GameProfile>");
    Check(TeknoGunSetup.Configure(repair,[new(1,mouse,"keyboard-1")])>0,"TeknoParrot setup writes the selected gun's raw-input device into the actual profile");
    var configuredTp=XDocument.Load(repairProfile);
    Check(configuredTp.Descendants("DeviceType").Count(e=>e.Value=="Mouse")==2 && configuredTp.Descendants("KeyboardKey").Any(e=>e.Value=="D1"),"TeknoParrot maps aim/trigger to the gun mouse and Start to its keyboard");
    Check(configuredTp.Descendants("FieldValue").Single().Value=="RawInput" && configuredTp.Descendants("BindName").Any(e=>e.Value=="Keep pedal") && TeknoGunSetup.Configure(repair,[new(1,mouse,"keyboard-1")])==0,"Automatic input setup is idempotent and preserves title-specific pedal controls");
    Check(OverlayControls.Read(repair,root,[new(1,mouse,"keyboard-1")]).Rows.Any(r=>r.Function=="Player 1 Light Gun" && r.Input=="P1 · "+I18n.T("Zielen / Mausbewegung")),"TeknoParrot aim binding is shown as movement instead of an unassigned button");
    string alienProfile=Path.Combine(tp,"UserProfiles","AliensExtermination.xml");
    File.WriteAllText(alienProfile,"<GameProfile><EmulationProfile>AliensExtermination</EmulationProfile><ConfigValues><FieldInformation><CategoryName>General</CategoryName><FieldName>Input API</FieldName><FieldValue>RawInput</FieldValue><FieldOptions><string>RawInput</string></FieldOptions></FieldInformation><FieldInformation><CategoryName>General</CategoryName><FieldName>Windowed</FieldName><FieldValue>0</FieldValue></FieldInformation><FieldInformation><CategoryName>General</CategoryName><FieldName>CustomResolution</FieldName><FieldValue>0</FieldValue></FieldInformation><FieldInformation><CategoryName>General</CategoryName><FieldName>ResolutionWidth</FieldName><FieldValue>1920</FieldValue></FieldInformation><FieldInformation><CategoryName>General</CategoryName><FieldName>ResolutionHeight</FieldName><FieldValue>1080</FieldValue></FieldInformation></ConfigValues><JoystickButtons><JoystickButtons><ButtonName>Player 1 Flame</ButtonName></JoystickButtons><JoystickButtons><ButtonName>Player 2 Flame</ButtonName></JoystickButtons><JoystickButtons><ButtonName>Player 1 Special</ButtonName></JoystickButtons></JoystickButtons></GameProfile>");
    var aliens=repair with {SourcePath=alienProfile};
    TeknoGunSetup.Configure(aliens,[new(1,"mouse-p1"),new(2,"mouse-p2")]);
    var alienXml=XDocument.Load(alienProfile);
    Check(alienXml.Descendants("JoystickButtons").Where(r=>r.Element("ButtonName")?.Value.EndsWith("Flame")==true).All(r=>r.Element("RawInputButton")?.Element("MouseButton")?.Value=="RightButton") && alienXml.Descendants("DevicePath").Any(e=>e.Value=="mouse-p2"),"Both Extermination flame weapons use the proper gun's right button");
    Check(alienXml.Descendants("JoystickButtons").Single(r=>r.Element("ButtonName")?.Value=="Player 1 Special").Element("RawInputButton")?.Element("MouseButton")?.Value=="MiddleButton","Extermination grenade remains separate from its flame weapon");
    Check(TeknoDisplaySetup.Configure(aliens,3840,2160) && !TeknoDisplaySetup.Configure(aliens,3840,2160) && File.Exists(alienProfile+".before-deadeye-display-fix"),"Aliens display setup follows the real display resolution, makes one backup and is idempotent");
    Check(XDocument.Load(alienProfile).Descendants("FieldInformation").Single(f=>f.Element("FieldName")?.Value=="ResolutionWidth").Element("FieldValue")?.Value=="3840" && !TeknoDisplaySetup.Configure(repair,3840,2160),"Display corrections use supported Aliens fields and preserve unrelated game profiles");
    Throws(() => GunSystems.ValidateMap(new() { ["mouse:99"] = "shoot" }), "Binding rejects invalid physical inputs");
    Throws(() => GunSystems.ValidateMap(new() { ["key:49"] = "delete-all" }), "Binding rejects unsupported actions");
    Check(GunSystems.ReaperConfiguration(new(OffscreenReload:false, Aspect:"4:3")).SequenceEqual(new[] {"ZS", "ZM", "ZN", "ZB", "ZX"}), "RS3 configuration applies aspect and reload and exits external mode without firing recoil");
    var remapped = XDocument.Parse(LaunchRules.MameController([new(1, mouse, ButtonMap:new() { ["mouse:2"]="shoot", ["key:49"]="start" })]));
    Check(remapped.Descendants("port").Single(p => (string?)p.Attribute("type") == "P1_BUTTON1").Value == "GUNCODE_1_BUTTON2", "Learned trigger binding reaches the actual MAME controller output");
    Check(remapped.Descendants("port").Single(p => (string?)p.Attribute("type") == "START1").Value == "KEYCODE_1", "MAME receives keyboard start mapping independently of gun numbering");
    var savedGuns = new LibraryStore(Path.Combine(root, "gun-data"));
    var gunState = LibraryState.Empty; gunState.Bindings.Add(new(1, mouse, "keyboard", "COM3", "rs3", "physical-container", new() { ["mouse:2"]="shoot" }, new(Aspect:"4:3"), true, new(){["trigger"]="mouse:2"})); savedGuns.Save(gunState);
    Check(savedGuns.Load().Bindings.Single().ButtonMap!["mouse:2"] == "shoot" && savedGuns.Load().Bindings.Single().Feedback!.Aspect == "4:3" && savedGuns.Load().Bindings.Single().ControlMap!["trigger"] == "mouse:2", "Physical assignment, captured controls, learned bindings and feedback survive cold reload");
    var gesture = new ExitGesture(); var now = DateTimeOffset.UtcNow; gesture.Key(0x31, true, now); gesture.Key(0x35, true, now);
    Check(!gesture.Ready(now.AddSeconds(1)) && gesture.Ready(now.AddSeconds(2)), "Exit requires a held chord, not coin or start alone");
    gesture.Key(0x35, false, now.AddSeconds(2)); Check(!gesture.Ready(now.AddSeconds(4)), "Releasing chord cancels exit");
    gesture.Key(0x35, true, now.AddSeconds(4)); gesture.Consume();
    gesture.Key(0x31, true, now.AddSeconds(5)); gesture.Key(0x35, true, now.AddSeconds(5));
    Check(!gesture.Ready(now.AddSeconds(8)), "Held/repeated exit keys cannot also close the menu after ending a game");
    gesture.Key(0x31, false, now.AddSeconds(8)); gesture.Key(0x35, false, now.AddSeconds(8));
    gesture.Key(0x31, true, now.AddSeconds(9)); gesture.Key(0x35, true, now.AddSeconds(9));
    Check(gesture.Ready(now.AddSeconds(11)), "Releasing both keys rearms the gun exit for closing the app");
    var hold = new TriggerHold(); hold.Button("trigger", true, 0);
    Check(!hold.Ready(9999) && hold.Ready(10000), "Overlay opens at exactly ten seconds, never before");
    hold.Button("trigger", true, 9000);
    Check(hold.Ready(10000), "Repeated down events do not restart the ten-second trigger hold");
    hold.Consume(); Check(!hold.Ready(30000), "A consumed hold cannot reopen the overlay while still pressed");
    hold.Button("trigger", false, 30001); hold.Button("trigger", true, 30002);
    Check(!hold.Ready(40001) && hold.Ready(40002), "Release rearms a fresh full ten-second hold");
    hold.Reset(); hold.Button("trigger", true, 0); hold.Button("trigger", false, 9999);
    Check(!hold.Ready(20000), "An early release cancels instead of accumulating repeated shots");
    var secondHold = new TriggerHold(); secondHold.Button("P2", true, 5000);
    Check(!secondHold.Ready(14999) && secondHold.Ready(15000) && !hold.Ready(15000), "Players have isolated hold durations");
    secondHold.Reset(); Check(!secondHold.Ready(90000), "Game end or disconnect clears stale trigger state");
    var deviceHold = new TriggerHold(); deviceHold.Button("gun-p1|mouse:1", true, 0);
    deviceHold.RetainDevices(new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "GUN-P1", "unrelated-new-device" });
    Check(deviceHold.Ready(10000), "Unrelated device arrival preserves a connected gun's full ten-second hold");
    deviceHold.RetainDevices(new HashSet<string>());
    Check(!deviceHold.Ready(20000) && !deviceHold.Pressed, "Removing the held gun cancels its hold without retaining a stuck button");
    string ctrlDir = Path.Combine(root, "overlay", "controllers"); Directory.CreateDirectory(ctrlDir);
    File.WriteAllText(Path.Combine(ctrlDir, "reaper.cfg"), LaunchRules.MameController([new(1, mouse, ButtonMap:new() { ["mouse:2"]="shoot", ["key:53"]="coin" })]));
    var mameControls = OverlayControls.Read(scarlet with { Source="mame" }, Path.Combine(root,"overlay"), []);
    Check(mameControls.Rows.Any(r => r.Player == 1 && r.Function == "Münze" && r.Input == "Taste 5") && mameControls.Rows.Any(r => r.Input == "P1 · Gun-Taste 2"), "Overlay reads the actual generated MAME bindings including a remapped trigger with readable labels");
    string tpOverlay = Path.Combine(root, "overlay.xml");
    File.WriteAllText(tpOverlay, new XDocument(new XElement("GameProfile", new XElement("ConfigValues", new XElement("FieldInformation", new XElement("FieldName", "Input API"), new XElement("FieldValue", "RawInput"))), new XElement("JoystickButtons", new XElement("JoystickButtons", new XElement("ButtonName", "Player 1 Start"), new XElement("InputMapping", "P1ButtonStart"), new XElement("RawInputButton", new XElement("DeviceType", "Keyboard"), new XElement("DevicePath", "keyboard"), new XElement("KeyboardKey", "D1"), new XElement("MouseButton", "None")))))).ToString());
    var tpControls = OverlayControls.Read(scarlet with { SourcePath=tpOverlay }, root, [new(1, mouse, "keyboard")]);
    Check(tpControls.Rows.Single().Player == 1 && tpControls.Rows.Single().Input == "P1 · D1", "Overlay retains TeknoParrot's title-specific start label and exact device assignment");
    Check(OverlayControls.Read(scarlet with { Source="pc" }, root, []).Rows.Length == 0, "Unknown game mappings stay unknown instead of becoming invented A/B assignments");
    var extraPlayers = XDocument.Load(tpOverlay);
    extraPlayers.Root!.Element("JoystickButtons")!.Add(new XElement("JoystickButtons",new XElement("ButtonName","Coin Chute 3"),new XElement("InputMapping","Coin3")),new XElement("JoystickButtons",new XElement("ButtonName","Coin Chute 4"),new XElement("InputMapping","")));
    extraPlayers.Save(tpOverlay);
    var allPlayers = OverlayControls.Read(scarlet with {SourcePath=tpOverlay},root,[new(1,mouse,"keyboard")]);
    Check(allPlayers.Rows.Select(r=>r.Player).SequenceEqual(new[]{1,3,4}) && StartupControls.ForPlayer(allPlayers,new(2,mouse,"keyboard")).Length==0,"P3/P4 coin inputs never appear as shared P1/P2 controls");
    var wrongPlayer=XDocument.Load(tpOverlay);
    wrongPlayer.Root!.Element("JoystickButtons")!.Add(new XElement("JoystickButtons",new XElement("ButtonName","Player 2 Gun Trigger"),new XElement("InputMapping","P1Button1"),new XElement("RawInputButton",new XElement("DeviceType","Mouse"),new XElement("DevicePath","mouse-p2"),new XElement("MouseButton","LeftButton"))));
    wrongPlayer.Save(tpOverlay);
    var fixedPlayer=OverlayControls.Read(scarlet with {SourcePath=tpOverlay},root,[new(2,"mouse-p2")]);
    Check(fixedPlayer.Rows.Last().Player==2 && StartupControls.ForPlayer(fixedPlayer,new(2,"mouse-p2")).Any(h=>h.Resolved&&h.ControlIds.Contains("trigger")),"TeknoParrot's explicit P2 label wins over stale P1 InputMapping metadata and resolves only the P2 device");
    var sortedHints=StartupControls.ForPlayer(new([new(0,"Test","Unknown","fixture"),new(1,"Coin","key:53","fixture","key:53"),new(1,"Trigger","mouse:1","fixture","mouse:1")],""),new(1,mouse));
    Check(sortedHints.Select(h=>h.Function).SequenceEqual(new[]{"Trigger","Coin","Test"})&&!sortedHints.Last().Resolved,"Resolved gun functions lead the legend while unknown mappings remain visibly unconfirmed");
    string tpDirectory=Path.Combine(root,"vendor-tekno");Directory.CreateDirectory(Path.Combine(tpDirectory,"GameProfiles"));
    string userProfile=Path.Combine(tpDirectory,"AliensArmageddon.xml"),vendorProfile=Path.Combine(tpDirectory,"GameProfiles","AliensArmageddon.xml");
    File.WriteAllText(userProfile,"<GameProfile><EmulationProfile>RawThrillsGUN</EmulationProfile><Patreon>true</Patreon><GamePath>keep-game</GamePath><ConfigValues>keep-settings</ConfigValues><JoystickButtons>keep-buttons</JoystickButtons></GameProfile>");
    File.WriteAllText(vendorProfile,"<GameProfile><EmulationProfile>RawThrillsGUN</EmulationProfile><Patreon>false</Patreon><EmulatorType>ElfLdr2</EmulatorType><GamePath /></GameProfile>");
    var staleVendorGame=scarlet with {SourcePath=userProfile,Executable=Path.Combine(tpDirectory,"TeknoParrotUi.exe")};
    Check(EmulatorSetup.ConfigurePaths(staleVendorGame)&&File.ReadAllText(userProfile).Contains("<Patreon>false</Patreon>")&&XDocument.Load(userProfile).Root!.Element("JoystickButtons")!.Value=="keep-buttons"&&XDocument.Load(userProfile).Root!.Element("GamePath")!.Value=="keep-game","CLI launch refreshes stale eligibility from installed official metadata while preserving game paths and input settings");
    Check(!EmulatorSetup.ConfigurePaths(staleVendorGame)&&File.Exists(userProfile+".before-deadeye-vendor-fix"),"Vendor metadata repair is idempotent and retains the original profile backup");
    string asciiTarget=Path.Combine(root,"elf-game");File.WriteAllText(asciiTarget,"");
    File.WriteAllText(userProfile,"<GameProfile><EmulatorType>ElfLdr2</EmulatorType><GamePath>Arcade — folder/game</GamePath><JoystickButtons>keep-buttons</JoystickButtons></GameProfile>");
    Check(EmulatorSetup.ConfigureTeknoAsciiPath(staleVendorGame,_=>asciiTarget) && XDocument.Load(userProfile).Root!.Element("GamePath")!.Value==asciiTarget && XDocument.Load(userProfile).Root!.Element("JoystickButtons")!.Value=="keep-buttons", "ElfLoader ASCII repair changes only the game path and preserves controls");
    Check(!EmulatorSetup.ConfigureTeknoAsciiPath(staleVendorGame,_=>throw new Exception("Should not resolve twice")) && File.Exists(userProfile+".before-deadeye-ascii-fix"), "ElfLoader path repair retains a backup and skips already repaired paths");
    string dolphin = Path.Combine(root,"Dolphin.exe"); File.WriteAllText(dolphin, ""); File.WriteAllText(Path.Combine(root,"portable.txt"), "");
    Directory.CreateDirectory(Path.Combine(root,"User","Config")); File.WriteAllText(Path.Combine(root,"User","Config","WiimoteNew.ini"), "[Wiimote1]\nButtons/A = `Click 1`\nButtons/B = `Click 2`\n[Wiimote2]\nButtons/A = `D2`\n");
    var dolphinControls = OverlayControls.Read(scarlet with { Source="pc", Executable=dolphin, Arguments=[] }, root, []);
    Check(dolphinControls.Rows.Any(r => r.Player == 1 && r.Function == "A" && r.Input == "`Click 1`") && dolphinControls.Rows.Any(r => r.Player == 2 && r.Input == "`D2`"), "Overlay reads separate Dolphin A/B mappings from the selected portable configuration");
    var calibration=new ReaperCalibration();
    Check(calibration.Trigger(true)==0xB0 && calibration.Trigger(true) is null && calibration.Step==0,"RS3 calibration starts once and ignores repeated trigger-down packets");
    foreach(byte command in new byte[]{0xB2,0xB4,0xB6,0xB8}) {calibration.Trigger(false);Check(calibration.Trigger(true)==command,"RS3 saves the next manufacturer target only after release");}
    Check(calibration.Saved && calibration.Cancel() is null && new ReaperCalibration().Cancel()==0xBA,"RS3 completion preserves the saved sequence; an unfinished sequence aborts without saving");
    Check(ReaperCalibration.Targets.SequenceEqual(new (double,double)[]{(.5,.5),(.1,.1),(.9,.9),(.9,.1)}),"RS3 calibration uses manufacturer target order and actual screen proportions");
    string wbfs=Path.Combine(root,"Dead Space.wbfs");byte[] disc=new byte[1024];Encoding.ASCII.GetBytes("WBFS").CopyTo(disc,0);disc[8]=9;disc[12]=1;Encoding.ASCII.GetBytes("RZJE69").CopyTo(disc,512);File.WriteAllBytes(wbfs,disc);
    var deadspace=scarlet with {Title="Dead Space Extraction",Executable=dolphin,Source="custom",Arguments=["-e",wbfs],WorkingDirectory=root};
    Check(DolphinSetup.DiscId(deadspace)=="RZJE69","Dolphin setup reads the actual WBFS disc ID instead of guessing from a filename");
    string pack=Path.Combine(root,"accuracy-pack");Directory.CreateDirectory(Path.Combine(pack,"GameSettings"));Directory.CreateDirectory(Path.Combine(pack,"Config","Profiles","Wiimote"));
    File.WriteAllText(Path.Combine(pack,"GameSettings","RZJE69.ini"),"[Controls]\nWiimoteProfile1 = DEADSPACE_P1\n");
    File.WriteAllText(Path.Combine(pack,"Config","Profiles","Wiimote","DEADSPACE_P1.ini"),"[Profile]\nIR/Total Yaw = 17.25\nIR/Total Pitch = 16.75\nExtension = Nunchuk\nButtons/A = OLD\nNunchuk/Buttons/C = LCONTROL\n");
    File.WriteAllText(Path.Combine(pack,"LICENSE"),"External fixture license");Directory.CreateDirectory(Path.Combine(root,"User","GameSettings"));
    string perGame=Path.Combine(root,"User","GameSettings","RZJE69.ini");File.WriteAllText(perGame,"[Core]\nCPUThread = False\n[Controls]\nWiimoteSource1 = 1\nWiimoteProfile1 = OTHER_GUN\n");
    Check(DolphinSetup.Configure(deadspace,pack,[new(1,"RS3")]),"Dolphin applies the separate RS3 title profile on the actual setup path");
    string managed=DolphinSetup.ProfilePath(deadspace)!;string managedText=File.ReadAllText(managed);
    Check(DolphinSetup.Value(managedText,"Profile","IR/Relative Input")=="False", "RS3 aim follows absolute cursor position instead of integrating stick velocity");
    Check(DolphinSetup.Value(managedText,"Profile","IR/Total Yaw")=="17.25" && DolphinSetup.Value(managedText,"Profile","Nunchuk/Buttons/C")=="`M` & !`Click 1`" && !managedText.Contains("LCONTROL"),"Dolphin retains title accuracy and replaces inaccessible RS3 Nunchuk buttons");
    Check(File.ReadAllText(perGame).Contains("CPUThread = False") && DolphinSetup.Value(File.ReadAllText(perGame),"Controls","WiimoteSource1")=="0" && File.Exists(perGame+".before-deadeye-input"),"Dolphin preserves unrelated overrides, backs up input settings and disables an unverified P2 device");
    Check(DolphinSetup.Value(File.ReadAllText(perGame),"Video_Hardware","VSync")=="False" && DolphinSetup.Value(File.ReadAllText(perGame),"Video_Settings","MSAA")=="1", "Extraction receives its local latency preset without overwriting global graphics settings");
    Check(DolphinSetup.Value(File.ReadAllText(perGame),"Video_Settings","ShaderCompilationMode")=="2" && DolphinSetup.Value(File.ReadAllText(perGame),"Video_Settings","WaitForShadersBeforeStarting")=="True", "Extraction selects Dolphin's Hybrid Ubershaders (2), not Exclusive Ubershaders (1)");
    var titleControls=OverlayControls.Read(deadspace,root,[new(1,"RS3")]);
    Check(titleControls.Rows.Any(r=>r.Function=="Stasis (C)"&&r.Input=="`M` & !`Click 1`") && titleControls.Rows.Any(r=>r.Function.StartsWith("Glow Worm")) && titleControls.Rows.All(r=>r.Player==1),"Game overlay reads the active per-game controls including stasis, shake and pending P2");
    var legend=StartupControls.ForPlayer(titleControls,new(1,"RS3"));
    Check(legend.Length==12 && !legend.Any(r=>r.Function.StartsWith("D-Pad/")||r.Function.StartsWith("Buttons/")),"Dead Space startup legend prefers named game actions over duplicate Wii controls");
    Check(legend.Any(r=>r.Function=="Schießen (B)"&&r.Input=="Abzug"&&r.ControlIds.SequenceEqual(new[]{"trigger"})),"Startup legend maps the active Dolphin B function to the physical RS3 trigger");
    Check(legend.Any(r=>r.Function=="Stasis (C)"&&r.Input.Contains("Seitentaste M / N ohne Grifftasten")&&r.ControlIds.Contains("side")),"Startup legend preserves negated button combinations instead of telling users to press both");
    Check(legend.Any(r=>r.Function.StartsWith("Nahkampf")&&r.Input.Contains(" + ")&&r.ControlIds.Contains("reload")&&r.ControlIds.Contains("side")),"Startup legend shows the physical two-button melee combination");
    Check(StartupControls.ForPlayer(titleControls,new(2,"RS3")).Length==0,"A prepared P1 Dolphin profile does not fabricate P2 game support");
    var learned=StartupControls.Resolve(new(1,"A","`B`","Dolphin", "`B`"),new(1,"RS3",ControlMap:new(){["side"]="key:66"}));
    Check(learned.Resolved&&learned.ControlIds.SequenceEqual(new[]{"side"}),"Startup legend follows learned physical controls rather than a fixed factory diagram");
    Check(!StartupControls.Resolve(new(1,"A","foreign","Dolphin","DInput/1/Foreign:Button 0"),new(1,"RS3")).Resolved,"Foreign device expressions stay unconfirmed");
    Check(StartupControls.ForPlayer(tpControls,new(1,mouse,"keyboard")).Single().ControlIds.SequenceEqual(new[]{"start"}),"TeknoParrot startup controls identify the assigned physical Start button");
    Check(!StartupControls.ForPlayer(tpControls,new(2,mouse,"keyboard")).Any(r=>r.Resolved),"A TeknoParrot P1 device cannot be described as P2");
    Check(StartupControls.ForPlayer(mameControls,new(1,mouse)).Any(r=>r.Function=="Münze"&&r.ControlIds.SequenceEqual(new[]{"coin"})),"MAME startup legend resolves the actual generated Coin key");
    Check(!StartupControls.Resolve(new(1,"Start","key:49","TeknoParrot · RawInput","P2|key:49"),new(1,mouse)).Resolved,"Conflicting profile player and device assignment is never presented as confirmed");
    var sinden=new GunBinding(1,"Sinden",SystemId:"sinden",ControlMap:new(){["pump"]="mouse:2"});
    Check(StartupControls.Resolve(new(1,"Reload","mouse:2","fixture","mouse:2"),sinden).ControlIds.SequenceEqual(new[]{"pump"})&&!StartupControls.Resolve(new(1,"Start","key:49","fixture","key:49"),sinden).Resolved,"Other gun models use learned physical controls without inheriting RS3 keyboard buttons");
    I18n.Language="en";
    Check(StartupControls.Hardware(new(1,"RS3")).First().Label=="Trigger"&&I18n.T("Spielsteuerung")=="Game controls","Startup legend and its physical labels use English by default");
    I18n.Language="de";
    string firstSettings=File.ReadAllText(perGame);DolphinSetup.Configure(deadspace,pack,[new(1,"RS3")]);Check(firstSettings==File.ReadAllText(perGame),"Dolphin title setup is idempotent");
    Check(!DolphinSetup.Configure(deadspace,pack,[new(1,"Sinden",SystemId:"sinden")]),"Dolphin never applies RS3 controls to another gun system");
    Check(DolphinSetup.ReaperButtons("RZJE69",new(1,"RS3",ControlMap:new(){["side"]="key:66"}))["Nunchuk/Buttons/C"]=="`B` & !`Click 1`","Dolphin honours a learned physical side-button mapping");
    Check(DolphinSetup.Configure(deadspace,pack,[p1,p2],26761),"Dolphin installs independent P1/P2 profiles when its gun bridge is available");
    string dsuP2Profile=File.ReadAllText(DolphinSetup.ProfilePath(deadspace,2)!);
    Check(DolphinSetup.Value(dsuP2Profile,"Profile","Device")=="DSUClient/1/DeadeyeGuns" && DolphinSetup.Value(dsuP2Profile,"Profile","IR/Right")=="`Accel Right`" && DolphinSetup.Value(File.ReadAllText(perGame),"Controls","WiimoteSource1")=="1","Dolphin P2 uses a separate native device and absolute float aim rather than the shared mouse");
    Check(DolphinSetup.Value(File.ReadAllText(DolphinSetup.ProfilePath(deadspace)!),"Profile","IR/Total Yaw")=="17.25" && DolphinSetup.Value(dsuP2Profile,"Profile","Nunchuk/Stick/Up")=="`Pad W`","Dolphin retains existing accuracy adjustments and Extraction's rotated weapon-selection controls");
    var dualLegend=OverlayControls.Read(deadspace,root,[p1,p2]);
    Check(StartupControls.ForPlayer(dualLegend,p2).Any(h=>h.Resolved&&h.ControlIds.Contains("trigger")) && StartupControls.ForPlayer(dualLegend,p2).Any(h=>h.Resolved&&h.ControlIds.Contains("side")&&h.ControlIds.Contains("reload")),"Dolphin P2 legend resolves shooting and the real two-button melee combination through the active profile");
    string model=Path.Combine(root,"Supermodel.exe");File.WriteAllText(model,"");Directory.CreateDirectory(Path.Combine(root,"Config"));
    string modelIni=Path.Combine(root,"Config","Supermodel.ini");File.WriteAllText(modelIni,"[ Global ] ; existing global section\nInputGunX2 = JOY2_XAXIS\nSoundVolume = 61\n");
    InputDevice[] modelDevices=[new("p2mouse","RS3 P2","mouse",true),new("Root#RDP_MOU","remote","mouse",false),new("p1mouse","RS3 P1","mouse",true),new("p2keys","RS3 P2","keyboard",true),new("p1keys","RS3 P1","keyboard",true)];
    var modelGame=deadspace with{Executable=model};
    Check(SupermodelSetup.Configure(modelGame,[new(1,"p1mouse","p1keys"),new(2,"p2mouse","p2keys")],modelDevices),"Supermodel resolves live physical devices and configures two separate players");
    var modelText=File.ReadAllText(modelIni);
    Check(DolphinSetup.Value(modelText,"Global","InputGunX")=="\"MOUSE1_XAXIS\"" && DolphinSetup.Value(modelText,"Global","InputGunX2")=="\"MOUSE2_XAXIS\"" && DolphinSetup.Value(modelText,"Global","InputStart2")=="\"KEY2_2\"" && modelText.Contains("SoundVolume = 61"),"Supermodel uses the emulator's reversed enumeration and separate P2 keyboard without overwriting other settings");
    var modelLegend=OverlayControls.Read(modelGame,root,[new(1,"p1mouse","p1keys"),new(2,"p2mouse","p2keys")],modelDevices);
    Check(StartupControls.ForPlayer(modelLegend,new(2,"p2mouse","p2keys")).Any(h=>h.Function=="Start"&&h.Resolved&&h.ControlIds.Contains("start")),"Supermodel's live reversed device enumeration resolves P2 Start to its physical button");
    var titleModel=modelGame with {SourcePath=Path.Combine(root,"lostwsga.zip")};
    DolphinSetup.WriteMerged(modelIni,"lostwsga",new Dictionary<string,string>{{"InputTrigger2","\"MOUSE1_LEFT_BUTTON\""},{"GunXOffset","17"}});
    Check(!StartupControls.ForPlayer(OverlayControls.Read(titleModel,root,[new(2,"p2mouse","p2keys")],modelDevices),new(2,"p2mouse","p2keys")).Single(h=>h.Function=="Trigger").Resolved,"A title override pointing P2 at P1 cannot produce a resolved P2 gun hint");
    SupermodelSetup.Configure(titleModel,[new(1,"p1mouse","p1keys"),new(2,"p2mouse","p2keys")],modelDevices);
    Check(DolphinSetup.Value(File.ReadAllText(modelIni),"lostwsga","InputTrigger2")=="\"MOUSE2_LEFT_BUTTON\"" && DolphinSetup.Value(File.ReadAllText(modelIni),"lostwsga","GunXOffset")=="17","Supermodel repairs stale per-title input overrides while preserving its calibration");
    SupermodelSetup.Configure(modelGame,[new(1,"p1mouse","p1keys")],modelDevices);
    Check(DolphinSetup.Value(File.ReadAllText(modelIni),"Global","InputGunX2")=="\"NONE\"","Supermodel clears unavailable P2 routing instead of assigning an unrelated joystick");
    string ra = Path.Combine(root, "retroarch.exe"), raConfig = Path.Combine(root,"overlay-retroarch.cfg"), raExtra = Path.Combine(root,"overlay-extra.cfg");
    File.WriteAllText(raConfig, "input_player1_gun_start = \"enter\"\ninput_player2_b = \"v\"\n"); File.WriteAllText(raExtra, "input_player1_gun_start = \"1\"\n");
    var raControls = OverlayControls.Read(scarlet with { Source="pc", Executable=ra, Arguments=["--config",raConfig,"--appendconfig",raExtra] }, root, []);
    Check(raControls.Rows.Any(r => r.Player == 1 && r.Function == "Start" && r.Input == "Taste 1") && raControls.Rows.Any(r => r.Player == 2 && r.Function == "B" && r.Input == "Taste v"), "RetroArch appended config overrides the base mapping and preserves P2 B");
    using var http = new HttpClient(new FixtureHttp());
    var cover = await new CoverService(http, Path.Combine(root, "covers")).Download("Point Blank", "fixture", CancellationToken.None);
    Check(cover is not null && File.Exists(cover), "Cover service downloads an exact match and saves local artwork");
    using var ambiguousHttp = new HttpClient(new FixtureHttp(true));
    var ambiguous = await new CoverService(ambiguousHttp, Path.Combine(root, "covers")).Download("Point Blank", "fixture", CancellationToken.None);
    Check(ambiguous is null, "Ambiguous cover titles are not silently guessed");
    LibraryStore.Merge(state, [scarlet with { Status = "needs-setup" }]);
    Check(state.Games.Single(g => g.Id == scarlet.Id).Status == "needs-setup", "Reimport invalidates playable verdict when game files disappear");
    var discoveries = InstallationFinder.Find([root]);
    Check(discoveries.Count == 3 && discoveries.Single(d => d.Kind == "tekno").Path == scarlet.Executable && discoveries.Any(d=>d.Name=="Supermodel"), "Installation search finds nested TeknoParrot, Dolphin and Supermodel fixtures and deduplicates paths");
    var browse = InstallationFinder.Browse(tp, false, [".exe"]);
    Check(browse.Entries.Any(e => !e.Directory && e.Path == scarlet.Executable) && !browse.Entries.Any(e => e.Name.EndsWith(".xml")), "Arcade picker filters applications and retains navigable folders");
    var folderPage = InstallationFinder.Browse(tp, true, []);
    Check(folderPage.Entries.All(e => e.Directory) && folderPage.Parent == root, "Folder selection cannot offer files and exposes correct parent");
    Throws(() => InstallationFinder.Browse(Path.Combine(root, "absent"), true, []), "Picker rejects vanished directory");
    string missingAsset = Path.Combine(root, "required.bin");
    var incomplete = LaunchRules.Validate(scarlet with { RequiredFiles = [missingAsset], Status = "tested" });
    Check(incomplete.Status == "needs-setup" && incomplete.SetupIssues!.Length == 1, "Required assets block and invalidate a previously tested game");
    File.WriteAllText(missingAsset,"restored");
    var recoveredCustom=incomplete with {Source="custom"};
    Check(LaunchRules.Prepare(recoveredCustom).FileName==recoveredCustom.Executable,"Restoring a required file unblocks a custom launch without preserving a stale import failure");
    File.Delete(missingAsset);
    File.WriteAllText(missingAsset, "asset");
    Check(LaunchRules.Validate(incomplete).Status == "unverified", "Restored assets unlock only file readiness, never claim gameplay");
    string handoff = Path.Combine(root, "spiele.json");
    var options = new[] { new { target = Path.Combine(root, "missing.exe"), cwd = root, requires = new[] {missingAsset}, arguments_array = new[] {"bad"} },
        new { target = scarlet.Executable, cwd = tp, requires = new[] { scarlet.SourcePath, missingAsset }, arguments_array = scarlet.Arguments } };
    File.WriteAllText(handoff, System.Text.Json.JsonSerializer.Serialize(new { games = new[] { new { id = 316, title = "Fixture collection game", system = "Arcade", priority = 1, two_player = "2", dual_gun = "not tested", notes = "", launch_options = options } } }));
    var collection = CollectionImporter.Read(handoff);
    Check(collection.Games.Count == 1 && collection.Games[0].Executable == scarlet.Executable && collection.Games[0].Status == "unverified", "Collection chooses the complete alternative and validates the actual TP GamePath");
    Check(collection.Games[0].Id == "inventory-316" && collection.Games[0].Favorite && collection.Games[0].RequiredFiles!.Length == 2, "Collection preserves stable IDs, priority and runtime dependencies");
    File.Delete(missingAsset);
    Check(CollectionImporter.Read(handoff).Games[0].Status == "needs-setup", "Collection keeps unavailable titles visible but blocked");
    var shared = LibraryState.Empty;
    LibraryStore.Merge(shared, [scarlet with { Id = "inventory-a" }, scarlet with { Id = "inventory-b", Title = "Other title in shared collection" }]);
    Check(shared.Games.Count == 2, "Separate games sharing one launcher remain separate inventory entries");
    string chd = Path.Combine(roms, "carnevil"); Directory.CreateDirectory(chd);
    string archive = chd + ".zip", emulator = Path.Combine(root, "mame.exe"); File.WriteAllText(emulator, "fixture");
    File.WriteAllText(handoff, System.Text.Json.JsonSerializer.Serialize(new { games = new[] { new { id = 67, title = "CarnEvil", system = "MAME", c_paths = new[] { chd, archive, Path.Combine(roms, "other-clone.zip") }, launch_options = new[] { new { target = emulator, cwd = root, requires = new[] { chd }, arguments_array = new[] { "carnevil" } } } } } }));
    var chdGame = CollectionImporter.Read(handoff).Games.Single();
    Check(chdGame.SourcePath == archive && chdGame.RequiredFiles!.Length == 2 && chdGame.Status == "needs-setup", "MAME collection requires the ROM archive beside its data folder without requiring unrelated clones");
    File.WriteAllText(archive, "fixture");
    Check(CollectionImporter.Read(handoff).Games.Single().Status == "unverified", "MAME collection becomes file-ready only when archive and data folder both exist");
    string mediaRoot = Path.Combine(root, "media"); Directory.CreateDirectory(mediaRoot);
    string image = Path.Combine(mediaRoot, "cover #1.png"); File.WriteAllText(image, "fixture");
    Check(MediaPaths.Url(image, mediaRoot, "media.reaper.local") == "https://media.reaper.local/cover%20%231.png", "Media URL escapes real files under the dedicated folder");
    Check(MediaPaths.Url(scarlet.Executable, mediaRoot, "media.reaper.local") is null && MediaPaths.Url(Path.Combine(root, "outside.png"), mediaRoot, "media.reaper.local") is null, "Media URL refuses executables and paths outside its folder");
    string link = Path.Combine(mediaRoot, "escape.png"); File.CreateSymbolicLink(link, image);
    Check(MediaPaths.Url(link, mediaRoot, "media.reaper.local") is null, "Media URL refuses symbolic links");
    Check(RuntimeCatalog.For("MSVCR100.dll", "x86") == "vc2010-x86" && RuntimeCatalog.For("MSVCR100.dll", "x64") == "vc2010-x64", "Legacy VC dependency matches program architecture, not Windows architecture");
    Check(RuntimeCatalog.For("xinput1_3.dll", "x86") == "directx" && RuntimeCatalog.For("xinput1_4.dll", "x64") is null, "DirectX legacy libraries are distinguished from OS components");
    Check(RuntimeCatalog.Get("arbitrary-url") is null && RuntimeCatalog.Get("vc2010-arm64") is null, "Installer catalog refuses arbitrary or unsupported package identities");
    string depDir = Path.Combine(root, "deps"); Directory.CreateDirectory(depDir);
    string native = Path.Combine(depDir, "game.exe");
    WriteNative(native, false, "msvcr100.dll", "xinput1_3.dll");
    var parsed = NativeImports.Read(native);
    Check(parsed.Architecture == "x86" && parsed.Imports.Any(i => i.Name == "msvcr100.dll" && !i.Delayed) && parsed.Imports.Any(i => i.Name == "xinput1_3.dll" && i.Delayed), "PE parser reads ordinary and delay imports without executing code");
    var depGame = GameImporter.Pc(native, "Dependency fixture");
    var absent = DependencyScanner.Scan([depGame], Path.Combine(root, "windows"));
    string secondExe = Path.Combine(depDir, "amdaemon.exe"), runtimeProfile = Path.Combine(depDir, "two-executables.xml");
    WriteNative(secondExe, true, "msvcp110.dll");
    new System.Xml.Linq.XDocument(new System.Xml.Linq.XElement("GameProfile", new System.Xml.Linq.XElement("GamePath", native), new System.Xml.Linq.XElement("HasTwoExecutables", true), new System.Xml.Linq.XElement("GamePath2", secondExe))).Save(runtimeProfile);
    var profileGame = depGame with { Source = "teknoparrot", SourcePath = runtimeProfile };
    Check(DependencyScanner.Scan([profileGame], root).Findings.Any(f => f.Binary == secondExe && f.PackageId == "vc2012-x64" && f.Missing && f.Required), "TeknoParrot second executable participates in the required dependency scan");
    File.WriteAllText(runtimeProfile, File.ReadAllText(runtimeProfile).Replace("<HasTwoExecutables>true</HasTwoExecutables>", "<HasTwoExecutables>false</HasTwoExecutables>"));
    Check(!DependencyScanner.Scan([profileGame], root).Findings.Any(f => f.Binary == secondExe), "Unused TeknoParrot second executable does not block single-executable profiles");
    Check(absent.Findings.Single(f => f.Dll == "msvcr100.dll").Missing && absent.Findings.Single(f => f.Dll == "msvcr100.dll").Required && !absent.Findings.Single(f => f.Dll == "xinput1_3.dll").Required, "Scan identifies required missing VC and optional delayed DirectX separately");
    WriteNative(Path.Combine(depDir, "msvcr100.dll"), true);
    Check(DependencyScanner.Scan([depGame], root).Findings.Single(f => f.Dll == "msvcr100.dll").Missing, "Wrong-architecture local DLL cannot falsely satisfy a dependency");
    WriteNative(Path.Combine(depDir, "msvcr100.dll"), false);
    Check(!DependencyScanner.Scan([depGame], root).Findings.Single(f => f.Dll == "msvcr100.dll").Missing, "Recheck observes the installed compatible DLL");
    File.WriteAllText(Path.ChangeExtension(native, ".runtimeconfig.json"), "{\"runtimeOptions\":{\"framework\":{\"name\":\"Microsoft.WindowsDesktop.App\",\"version\":\"8.0.2\"}}}");
    Check(DependencyScanner.Scan([depGame], root, (_, _, _) => false).MissingPackages.Contains("dotnet8-x86"), "Managed runtime configuration selects the correct .NET generation and architecture");
    Check(!DependencyScanner.Scan([depGame], root, (_, _, _) => true).MissingPackages.Contains("dotnet8-x86"), "Managed runtime rescan observes an installed compatible framework");
    string legacy = Path.Combine(depDir, "legacy-helper.exe");
    WriteManaged(legacy, "v2.0.50727");
    var legacyGame = depGame with { Helpers = [new(legacy, [], depDir)] };
    Check(DependencyScanner.Scan([legacyGame], root, (_, _, _) => false).MissingPackages.Contains("netfx35"), "CLR 2 helper is detected without a modern runtimeconfig file");
    Check(!DependencyScanner.Scan([legacyGame], root, (_, _, _) => true).MissingPackages.Contains("netfx35"), "Classic framework rescan observes installation");
    File.WriteAllText(legacy + ".config", "<configuration><startup><supportedRuntime version=\"v4.0\"/></startup></configuration>");
    Check(!DependencyScanner.Scan([legacyGame], root, (_, _, _) => false).MissingPackages.Contains("netfx35"), "CLR 4 startup override avoids unnecessary CLR 2 installation");
    File.Delete(legacy + ".config"); WriteManaged(legacy, "v4.0.30319");
    Check(!DependencyScanner.Scan([legacyGame], root, (_, _, _) => false).MissingPackages.Contains("netfx35"), "CLR 4 executables do not require NetFx3");
    Check(RuntimeCatalog.Get("netfx35")?.Url.StartsWith("https://download.microsoft.com/") == true, "Classic framework catalog uses the official Microsoft installer");
    string optionalRoot = Path.Combine(depDir, "optional.exe"), requiredRoot = Path.Combine(depDir, "required.exe");
    WriteNative(optionalRoot, false, delayed: "shared.dll"); WriteNative(requiredRoot, false, "shared.dll");
    WriteNative(Path.Combine(depDir, "shared.dll"), false, "msvcr120.dll");
    var joined = GameImporter.Pc(optionalRoot, "Required after optional") with { RequiredFiles = [requiredRoot] };
    Check(DependencyScanner.Scan([joined], root).Findings.Any(f => f.Dll == "msvcr120.dll" && f.Missing && f.Required), "A required import reached after a delay import still blocks a broken launch");
    Throws(() => NativeImports.Read(handoff), "Malformed executable is rejected without loading it");
    byte[] updateBytes = new byte[2048]; new Random(7).NextBytes(updateBytes);
    string digest = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(updateBytes)).ToLowerInvariant();
    string releaseJson = System.Text.Json.JsonSerializer.Serialize(new { draft = false, prerelease = false, tag_name = "v0.3.4", body = "Test changes", assets = new[] { new { name = "Deadeye-Arcade-0.3.4-Setup-x64.exe", browser_download_url = "https://github.com/sthamann/deadeye-arcade/releases/download/v0.3.4/Deadeye-Arcade-0.3.4-Setup-x64.exe", digest = "sha256:" + digest, size = updateBytes.Length } } });
    var release = AppUpdates.Read(releaseJson, new Version(0, 3, 3, 0))!;
    Check(release.Version == "0.3.4" && release.Sha256 == digest, "Updater selects a newer stable installer and its SHA-256 digest");
    Check(AppUpdates.Read(releaseJson, new Version(0, 3, 4, 0)) is null && AppUpdates.Read(releaseJson, new Version(0, 4, 0, 0)) is null, "Updater never offers the same version or a downgrade");
    Check(AppUpdates.Read(releaseJson.Replace("\"prerelease\":false", "\"prerelease\":true"), new Version(0, 3, 3, 0)) is null, "Automatic updates exclude prereleases");
    Throws(() => AppUpdates.Read(releaseJson.Replace("https://github.com/", "https://example.com/"), new Version(0, 3, 3, 0)), "Updater rejects foreign download addresses");
    Throws(() => AppUpdates.Read(releaseJson.Replace(digest, "invalid"), new Version(0, 3, 3, 0)), "Updater rejects missing or malformed digests");
    using var updateClient = new HttpClient(new UpdateFixture(updateBytes));
    string updateDirectory = Path.Combine(root, "updates");
    string downloaded = await AppUpdates.Download(updateClient, release, updateDirectory, null);
    Check(File.ReadAllBytes(downloaded).SequenceEqual(updateBytes), "Verified installer downloads reach the final file");
    using var corruptClient = new HttpClient(new UpdateFixture(new byte[updateBytes.Length]));
    bool corruptRejected = false;
    try { await AppUpdates.Download(corruptClient, release, updateDirectory, null); } catch (InvalidDataException) { corruptRejected = true; }
    Check(corruptRejected && !File.Exists(downloaded + ".partial") && File.ReadAllBytes(downloaded).SequenceEqual(updateBytes), "A corrupt download is rejected and preserves an earlier verified installer");
    using var cancel = new CancellationTokenSource(); cancel.Cancel();
    bool cancelled = false;
    try { await AppUpdates.Download(updateClient, release, updateDirectory, null, cancel.Token); } catch (OperationCanceledException) { cancelled = true; }
    Check(cancelled && !File.Exists(downloaded + ".partial"), "Cancelled updates clean partial downloads");
    Check(new AppSettings().CheckForUpdates && System.Text.Json.JsonSerializer.Deserialize<AppSettings>("{}", JsonDefaults.Options)!.CheckForUpdates, "Automatic update checks default on for new and existing libraries");
    if (args.Length > 1)
    {
        var actual = CollectionImporter.Read(args[1]);
        using var fixture = System.Text.Json.JsonDocument.Parse(File.ReadAllText(args[1]));
        var rows = fixture.RootElement.GetProperty("games").EnumerateArray().ToArray();
        Check(actual.Games.Count == rows.Length && actual.Games.Select(g => g.Id).Distinct().Count() == rows.Length, "Collection fixture imports every distinct entry, including absent media");
        Check(actual.Games.Count(g => g.Priority == 1) == rows.Count(r => r.TryGetProperty("priority", out var n) && n.GetInt32() == 1), "Collection fixture preserves priority selection");
        File.WriteAllText(Path.Combine(args[0], "collection-import-check.json"), System.Text.Json.JsonSerializer.Serialize(actual, JsonDefaults.Options));
    }
    var enriched = LibraryState.Empty;
    enriched.Games.Add(scarlet with { Favorite = true, Status = "tested", Description = "Old description" });
    var metadata = new GameEnrichment(scarlet.Id, scarlet.Title, scarlet.Platform, "Fight undead creatures in a cinematic arcade rail shooter.", 2018,
        "SEGA ALLS", ["https://segaarcade.com/games/house-of-the-dead-scarlet-dawn-theatre"]);
    LibraryEnrichment.Apply(enriched, new([metadata]));
    Check(enriched.Games[0].Description == metadata.Description && enriched.Games[0].ReleaseYear == 2018 && enriched.Games[0].Hardware == "SEGA ALLS", "Game information reaches the real library model");
    Check(enriched.Games[0].Arguments.SequenceEqual(scarlet.Arguments) && enriched.Games[0].Favorite && enriched.Games[0].Status == "tested", "Enrichment preserves launches, favourites and actual verification status");
    var enrichedStore = new LibraryStore(Path.Combine(root, "enriched")); enrichedStore.Save(enriched);
    Check(enrichedStore.Load().Games[0].MetadataSources!.Single() == metadata.MetadataSources![0], "Information and provenance survive a cold library reload");
    LibraryStore.Merge(enriched, [scarlet]);
    Check(enriched.Games[0].Description == metadata.Description && enriched.Games[0].ReleaseYear == 2018 && enriched.Games[0].Hardware == "SEGA ALLS", "Reimporting an old-format game preserves enriched information");
    var before = enriched.Games[0];
    Throws(() => LibraryEnrichment.Apply(enriched, new([metadata with { Description = "Must not partially apply" }, metadata with { Id = "wrong" }])), "Wrong game identity rejects the complete enrichment batch");
    Check(enriched.Games[0] == before, "A rejected batch does not partially mutate the library");
    Throws(() => LibraryEnrichment.Apply(enriched, new([metadata with { ReleaseYear = 9999 }])), "Impossible release year is rejected");
    Throws(() => LibraryEnrichment.Apply(enriched, new([metadata with { Cover = Path.Combine(root, "missing.jpg") }])), "Missing new artwork cannot silently enter the library");
    Throws(() => LibraryEnrichment.Apply(enriched, new([metadata with { MetadataSources = ["file:///private/source"] }])), "Private paths are not accepted as public provenance links");
    Console.WriteLine($"\n{checks} meaningful core checks passed.");
}
finally { Directory.Delete(root, true); }

void WriteManaged(string path, string version)
{
    var metadata = new System.Reflection.Metadata.Ecma335.MetadataBuilder();
    metadata.AddModule(0, metadata.GetOrAddString("fixture"), metadata.GetOrAddGuid(Guid.NewGuid()), default, default);
    var pe = new System.Reflection.PortableExecutable.ManagedPEBuilder(
        new System.Reflection.PortableExecutable.PEHeaderBuilder(),
        new System.Reflection.Metadata.Ecma335.MetadataRootBuilder(metadata, version),
        new System.Reflection.Metadata.BlobBuilder());
    var blob = new System.Reflection.Metadata.BlobBuilder(); pe.Serialize(blob); File.WriteAllBytes(path, blob.ToArray());
}

void WriteNative(string path, bool x64, string? imported = null, string? delayed = null)
{
    byte[] bytes = new byte[1024]; using var memory = new MemoryStream(bytes); using var writer = new BinaryWriter(memory);
    void U16(int offset, ushort value) { memory.Position = offset; writer.Write(value); }
    void U32(int offset, uint value) { memory.Position = offset; writer.Write(value); }
    U16(0, 0x5a4d); U32(0x3c, 0x80); U32(0x80, 0x4550); U16(0x84, x64 ? (ushort)0x8664 : (ushort)0x14c); U16(0x86, 1);
    int opt = 0x98, optSize = x64 ? 240 : 224; U16(0x94, (ushort)optSize); U16(0x96, 0x102); U16(opt, x64 ? (ushort)0x20b : (ushort)0x10b);
    U32(opt + 32, 0x1000); U32(opt + 36, 0x200); U32(opt + 56, 0x2000); U32(opt + 60, 0x200); U16(opt + 68, 3);
    int directory = opt + (x64 ? 112 : 96); U32(directory - 4, 16);
    int section = opt + optSize; memory.Position = section; writer.Write(Encoding.ASCII.GetBytes(".rdata\0\0"));
    U32(section + 8, 0x200); U32(section + 12, 0x1000); U32(section + 16, 0x200); U32(section + 20, 0x200); U32(section + 36, 0x40000040);
    if (imported is not null) { U32(directory + 8, 0x1000); U32(directory + 12, 40); U32(0x20c, 0x1080); memory.Position = 0x280; writer.Write(Encoding.ASCII.GetBytes(imported + "\0")); }
    if (delayed is not null) { U32(directory + 13 * 8, 0x1040); U32(directory + 13 * 8 + 4, 64); U32(0x240, 1); U32(0x244, 0x10b0); memory.Position = 0x2b0; writer.Write(Encoding.ASCII.GetBytes(delayed + "\0")); }
    File.WriteAllBytes(path, bytes);
}

sealed class FixtureHttp(bool ambiguous = false) : HttpMessageHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        string path = request.RequestUri!.AbsolutePath;
        HttpContent content = path.Contains("autocomplete") ? new StringContent(ambiguous ? "{\"data\":[{\"id\":1,\"name\":\"Point Blank\"},{\"id\":2,\"name\":\"Point Blank\"}]}" : "{\"data\":[{\"id\":1,\"name\":\"Point Blank\"}]}") :
         path.Contains("grids") ? new StringContent("{\"data\":[{\"url\":\"https://cdn2.steamgriddb.com/grid/fixture.png\"}]}") : new ByteArrayContent([137, 80, 78, 71]);
        if (!path.Contains("api")) content.Headers.ContentType = new("image/png");
        return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK) { Content = content });
    }
}

sealed class UpdateFixture(byte[] bytes) : HttpMessageHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK) { RequestMessage = request, Content = new ByteArrayContent(bytes) });
    }
}
